### ISSUE TITLE
MEGA - Corrupted rar file

### ISSUE THREAD

**Issue by marviobezerra** [pyload/pyload#1017]
The download for Mega Site works, by using the pyLoad rar files are corrupted. 

"Unexpected end of the file"

https://mega.co.nz/#!YkF0ULyJ!R5O4wZQjuQInGn3-Oh9T2K53uB7zqAFYxgxgrbBdpIA

**Comment by valadrem** [comment]
Hi, I'm suffering the same bug. After some research, I've tracked it down to this line:
```python
        chunks = int(math.ceil(os.path.getsize(file_crypted) / chunk_size))
```
In Python 3 the default behaviour is to compute divisions as floating point numbers, so this works as intended, but if you're using Python 2.x, since both the file size returned by getsize() and chunk_size are integers, the result of the division is also an integer and it's incorrectly rounded.
Eg: in Python 3 `int(math.ceil(32769/2**15))` returns 2, whereas in Python 2.7 it returns 1.

The quickest approach to solve this could be casting chunk_size to float, which produces the same results both in Python 2.x and Python 3.
```python
        chunks = int(math.ceil(os.path.getsize(file_crypted) / float(chunk_size)))
```
