### ISSUE TITLE
CRC Mismatch (extract archive)

### ISSUE THREAD

**Issue by zlep** [pyload/pyload#1029]
Since the last update of the extract archive plugin I'm getting 

CRC Mismatch
ERROR   ExtractArchive: xxxx.part01.rar | Extract failed

error in 90% of my packages.

No further info in the logs.

What's wrong? It worked perfectly for years and not it is broken.

Edit: And by the way: If I extract the archives manually it works great. So no CRC error. It must have to do with the plugin.

**Comment by Gutz-Pilz** [comment]
guess. thats part of the password issue

**Comment by zlep** [comment]
Hm, not sure. It extracts some and some not.
My guess is that it has something to do if it's a folder which has to be extracted or a file. But I'm not absolutely sure about it.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8848a359a43316fb346b728d1d79d7b72d27e5a0
Please reopen if not fixed.

**Comment by zomed** [comment]
Not sure what has happened, but since some days I also get CRC errors while extracting:

33	28.03.2015 21:44:29	ERROR	ExtractArchive: filename.rar | CRC mismatch | folder/filename.r27 : packed data checksum error in volume /folder/folder/folder/folder/zfilename.part26.rar
234	?	?	folder/filename.r27 - checksum error

More strange is, when I restart the files with the CRC errors, I do have luck in the most cases and the archive can be extracted. Hence there might be something wrong with the Download itself? (Hoster is uploaded.to)

**Comment by N3rv0us** [comment]
I got the same error. The file size is correct but the file seems to be corrupted. I had this issue with different uploads, so I don't think they uploads were corrupted.
Setting the max connections per download to 1 also didn't solve the problem (I saw, that the chunk limit is set to 1 by script right?)

**Comment by Grauen** [comment]
Same here. Big files get corrupted. In my case it's every rar archive that has been split.

**Comment by GammaC0de** [comment]
@Grauen Please provide sample URL(s) with the problem
