### ISSUE TITLE
uploaded.to 'ascii' codec can't encode character u'\u2026' in position 66: ordinal not in range(128)

### ISSUE THREAD

**Issue by StarScream159** [pyload/pyload#1110]
I am now getting an error on uploaded.to or .net. It seems as though the file name is too long so it is truncated with the 'HORIZONTAL ELLIPSIS' (U+2026) Unicode character, as in the log I see it gets truncated.

File example that doesn't work:
//uploaded.net/file/r3euzg1l/The.Big.Bang.Theory.S08E13.720p.HDTV.X264-DIMENSION.mkv

File example that does work:
//uploaded.net/file/k0uwcufh/NC14.BDRip.x264-SPARKS.mkv

![pyload](https://cloud.githubusercontent.com/assets/6002500/5977977/47a4e9a4-a86a-11e4-93f5-b2c8b6ab425f.png)

**Comment by kasperj** [comment]
Same issue for me, murphys rule that this happens at the same time as all the multihoster don't support uploaded anymore

**Comment by ams36787** [comment]
same here

**Comment by Nepomuk** [comment]
I can confirm this as well. As it seems, the plugin parses the HTML site for the filename with [this line](https://github.com/pyload/pyload/blob/stable/module/plugins/hoster/UploadedTo.py#L32). The problem is, that uploaded changed their UI and only displays the truncated filename:

    <a href="file/a37i9798" id="filename">DDLValley.rocks_12.Monkeys.&hellip;mkv</a>

Nowhere on the HTML site the full string of the file is given, only after you click. I'm not familiar with plugin development, so for me there is no obvious solution for this problem. But maybe someone of you has an idea how to fix that.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/fb6585452b8dc10f21005293dd3b9fbb5c41073a
