### ISSUE TITLE
Ram usage too high -> killed

### ISSUE THREAD

**Issue by c0rrre** [pyload/pyload#1149]
hi,

I got a problem since 1 or 2 days.
Im running pyload on the cubietruck (arm dualcore 1Ghz and 2GB RAM)...

Since 1-2 days pyload gets killed, cause it uses the whole 2 GB ram oO
And its loading pretty slow on start.
Just ran a 2 file download and no error message in debug log.
No extract or other high-ram-usage progs running at this moment.

Could someone please help me

greetz

**Comment by nomad71** [comment]
Had the same Problem. 

Found the cause and a solution, but not the root of it.

In the pyload-Folder there is a file called files.db. Its the database that contains your downloadlist (files, URL, size, folder etc.). Normaly this is just a couple Kb for me. In my case it was 88 Mb (!). Having just a Raspberry Pi this made pyLoad easily beeing blown up to use the whole RAM.

All you have to do is to stop pyLoad, delete this file, start pyLoad again. BUT BE AWARE: this will remove every entry in the queue as well as in the collector.

Since you said its just two files you had in in you list, this will hopefully not cause too much trouble.

I will have a look into the blown up db over the weekend to see whats going on. There were some changes made over the last few days, maybe thats connected. But im currently on my phone - not ideal for database-inspection ;)

Please let me know if that worked for you and what size your files.db is.

**Comment by immenz** [comment]
I've had that issue also (very large files.db).

But in my case the broken extract archive was the cause. After my changes the problem seems to be gone. 

> No extract or other high-ram-usage progs running at this moment.
@c0rrre 
Did you have the extractarchive plugin activated?

**Comment by nomad71** [comment]
@immenz 
 Thank you for mentioning the loss of the user ... didn't notice this!

**Comment by c0rrre** [comment]
thanks for your help :) works for me

@immenz extractarchive is activated

**Comment by immenz** [comment]
Then it was probably the same behavior I discovered with the last version of ExtractArchive I mentioned above.

Think this Issue can be closed.
