### ISSUE TITLE
[ExtractArchive] Add arguments to events

### ISSUE THREAD

**Issue by nomad71** [pyload/pyload#1243]
In #1207 @immenz explained some functionality about dispatchEvent to me. He also already mentioned that not all events give a plethora of arguments. The current state (at least for ExtractArchive) is this:
```
Line 185	self.manager.dispatchEvent("all_archives_extracted")
Line 186	self.manager.dispatchEvent("all_archives_processed")
Line 332	self.manager.dispatchEvent("archive_extracted", pyfile, archive.out, archive.filename, new_files)
Line 339	self.manager.dispatchEvent("package_extracted", pypack)
Line 343	self.manager.dispatchEvent("package_extract_failed", pypack)
Line 474	self.manager.dispatchEvent("archive_extract_failed", pyfile)
```

Is there an argument that can be made against adding the args that are already given with "archive_extracted" to the other events? Especially "all_archives_extracted" and "all_archives_processed". Otherwise I would request adding pyfile, archive.out, archive.filename and new_files to them as well. Preferably in the same order.

Maybe this could also be standardised internally in a futrue releases, so that some basic arguments are always given by default, regardles of the plugin/hook?

Thanks!

**Comment by immenz** [comment]
I don't think that some basic arguments could be given by default, because the event depends on, well, the event which happens. For example you can't give archive names if there aren't any archives downloaded etc. 

But I understand what you want. You want to use all_archives_extracted to be sure you don't interfere with still downloading ones but could not use it for external programs because you haven't the names or locations of the files.
Problem is that these events were called in a position where the function isn't aware of all packages which were allready extracted, it only knows when last package has been extracted. 

But I will look into it and check if there is another possibility.

**Comment by nomad71** [comment]
For me personally it would be enough to have the package-name and especially -folder (if specified) given. But thinking beyond my needs and in terms of versatility it would be better if there were as many args as possible (in a meaningfull way of course) for every given event. And the more unified this is, the better to use.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/a54c4268e402a3a1509c33d0b2de6f4336583416
