### ISSUE TITLE
webshare.cz maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by xDereCx** [pyload/pyload#1503]
dont know how much is that issue related to my config or i missed something, but working ok until today, after update it fails to download from above hoster with error maximum recursion depth exceeded while calling a Python object
logs :
http://paste.debian.net/230957/
http://paste.debian.net/230968/

**Comment by Mister-XY** [comment]
the same here with uploadet.

**Comment by Camp3r** [comment]
the same here with share online...

**Comment by vuolter** [comment]
Checking...

**Comment by acid112** [comment]
Whats wrong with you.
You make some a lot of changes an "tweaks" and nothing works any more....
You have closed this issue but nothing happens. You just change the versions. Great !
I cant download anything...
I think you dont test anything if you change the code. Everything works before you put your hands into the code...
If you have fix this issue, i will deactivate updates.

**Comment by vuolter** [comment]
@acid112 You're really "acid". XD
The piece of code I'm updating is more than five years old... please follow these istructions before comment: http://forum.pyload.org/viewtopic.php?f=7&t=4335
I changed just the version, because I already fix this issue, but forgot to increase the plugin version, so the update was not released, simply. :P

**Comment by xDereCx** [comment]
@acid112 for me its starts working mate
