### ISSUE TITLE
UptoboxCom plugin should have multiDL=False

### ISSUE THREAD

**Issue by doudz** [pyload/pyload#1530]
Currently UptoboxCom plugin has multiDL=True but Uptobox doesn't allow multiple download at the same time.

So currently when you download from different hosters, links from Uptobox just fill the queue and other links (from other hosters) are waiting ...

**Comment by lazlev** [comment]
uptobox allows multiple downloads at the moment...

**Comment by doudz** [comment]
Not for me, there's 45min delay between download

**Comment by joberreiter** [comment]
New plugin version with #1826.

**Comment by youlJunior** [comment]
Same problem here, when I put multiple Uptobox urls, Pyload launch them in parallel.

I manually put "False" in Uptobox hoster, and Pyload only dl Uptobox links one by one.

And what is magical is that the XFSHoster detect when it's "Happy hour" on Uptobox, en then it allow Pyload to dl Uptobox links in parallel ;-)

**Comment by vuolter** [comment]
Why don't use the DL_LIMIT_PATTERN for god sake! XD

**Comment by youlJunior** [comment]
Lol.

I already checked about that, but I don't really see how we can use that for Uptobox case.

If I look in the code of SimpleHoster class, I expect that it will act like that : 
- all dls will be started
- one dl will get a slot, and it will start downloading
- all other dls will have an error about time to wait (45 mins on uptobox)
- if we set the DL_LIMIT_PATTERN correctly, it will catch that, and all other dls will retry with a wait time of 45mins : 
````
self.retry(1, wait_time, _("Download limit exceeded"))
````
BUT the problem is that the retry has a first parameter of "1", so 45 minutes after : 
- all other dls will retry
- one will have a slot and strat downloading
- all others will have the time error, but the retry will fail because the max number of retry was setted to "1" !!!
