### ISSUE TITLE
Problem loading share-online as free user

### ISSUE THREAD

**Issue by Vince-IN** [pyload/pyload#1539]
Since the latest update, my Raspberry is having multiple problems downloading files from ShareOnline.
a) offline files are not detected as offline (Message: download limit exceeded)
b) When free user limiit is reached, pyload gives out wrong error message"Premium account needed"
c) Online files, loadable without Premium account and actually "free user slot" available, pyload although can't download file. Asking Captcha every ~15 Seconds, giving out "Wrong Captcha" or "No valid captcha solution received", every time. Doesn't matter if solving Captcha in GUI or via Captchatrader.

See full log for Error c) here:
http://www50.zippyshare.com/v/E3LkQLtX/file.html

**Comment by nomad71** [comment]
@ b) Have a look at #1497.

The error state "full" and "limitfree" are essentially the same. Share-Online says the files are inaccessible due to traffic but that's not true. They regulate traffic by adjusting the bandwidth for free user (50 KB/s ~ 500KB/s is what I saw). This message is shown to make you buy a premium account. It's shown in (seemingly) random selected files. And it changes in about a weeks time (more or less). It's their way to deal with too heavy use of free downloads. Many hoster  have mechanisms like this.

The latest changes in this regard just spare you 3 minutes of time. The standard procedure for unknown states is to wait a minute and repeat up to three times, which makes sense if its just a ssl timeout or something. But as I said this condition persists for days or weeks - it wouldn't make too much sense to wait until that day. 

@ c) I use a raspberry, too. And I've noticed similar behaviour. I didn't have time to dig through the log so I didn't open an issue yet and I wasn't sure this isn't just my fault by having several other things running at the same time. I think it has to do with CPU load. This behaviour is very obvious when there are several files downloaded at maximum speed. Its not limited to share-online but every captcha-request. But again ...it may just be me demanding too much from a raspberry.

Try limiting the number of parallel downloads, the number of chunks to 1 and limit the overall speed. If that improves the situation it may very well be a load issue.

**Comment by Vince-IN** [comment]
The difference @ b) is that in the earlier version tried it several times (about 5 i think) before setting "full". There was a much bigger chance to hit one of the free user slots and by setting RestartFailed to an hour or less you were able to increase chances. That method isn't practicable any more

@ c) On my raspberry it surely can't by a problem with the CPU load. I neither have running other applications running the same time nor do I download more files the same time. In the log I postet you can see, that I am only running  this one file.

**Comment by nomad71** [comment]
c) Was just a hypothesis ... ;)

b) I don't think that they do have such a thing as 'free slots' - in spite of what the site says. I've been harassing their service quite intensely for a while now. Usually you can download files just fine. Then you encounter this one file that seems to be on the busiest server ever. And you will get 'no free slots available' all the time - no matter how often you try*.
Now if you have a dozen files waiting you will notice a curious thing. After quite some time (often days) you finally will be able to download these files - all of them. I have a hard time believing that this a coincident. In my opinion they do this to pressure you into buying a premium account. They just choose files (maybe randomly) and make them have no 'free slots'. I also noticed that once this message is gone, you won't see it again. Another indicator that this isn't due to traffic or something like this, but rather made up.

* You can modify the loop to repeat a 100 times or more - didn't get me one of those elusive free slots, just ever more waiting time. You can try it yourself. I would be surprised if you get a different result, but I'm happy to concede that I'm wrong. I have no insider information on this after all, just my observations.

My over all solution to this problem is usually to use a mirror ...

**Comment by GammaC0de** [comment]
Hi,
`OFFLINE_PATTERN` updated.
If you get a "no free slot" message, please post html or at least a screenshot.

**Comment by Vince-IN** [comment]
In my understanding trying it many times in a short distance won't guarantee success, but when I made pyload try it 3 to 5 times every about ten minutes, I usualy could load one of the files every about 12 to 24 hours.
So I don't think it's impossible

Example links for "no free user slots" are
http://www.share-online.biz/dl/4V5JYERMIC
http://www.share-online.biz/dl/1YDKYERMBK

Here the log for b):
http://www2.zippyshare.com/v/WAIAo4bs/file.html

**Comment by GammaC0de** [comment]
Ok,
PR Updated

**Comment by nomad71** [comment]
I will modify my procedure accordingly and test angain. If this is the way it works, reverting the latest change would indeed make sense.
I am currently using Share-Online.Biz and I don't want to postpone the current downloads, so I will test it afterwards.
I will be using the links you provided.

**Comment by sraedler** [comment]
please close it's working
