### ISSUE TITLE
Issue: pyload latest version, nothing is working anymore

### ISSUE THREAD

**Issue by venious** [pyload/pyload#1619]
can not add premium accounts, if so, account isnt recognized. no scripts are running anymore. i want the old running version back please, can you revert to sundays version?

**Comment by mobo95** [comment]
Same problem.

I had to delete completely pyload and  reinstall again because updates broken it.
I can't add premium accounts using webif.
I have to change manually the file accounts.conf
Also, i have problem with easybytez. Sometime i get this:
458	30.07.2015 18:08:24	WARNING	Download failed: Under.the.Dome.S01E02.part01.rev | global name 'mimetypes' is not defined

**Comment by mobo95** [comment]
And why these logs for every download? DEBUG mode is disabled and i see this:

30.07.2015 17:08:17	WARNING	HOSTER EasybytezCom[5825] : Config option `use_premium` not found, use default `True`
320	30.07.2015 17:08:17	INFO	HOSTER EasybytezCom[5825] : Updating file info...
321	30.07.2015 17:08:18	INFO	HOSTER EasybytezCom[5825] : File name: Under.the.Dome.S01E01.part10.rar
322	30.07.2015 17:08:18	INFO	HOSTER EasybytezCom[5825] : File size: 526385152 bytes
323	30.07.2015 17:08:18	INFO	HOSTER EasybytezCom[5825] : File status: online
324	30.07.2015 17:08:18	INFO	HOSTER EasybytezCom[5825] : Looking for direct download link...

**Comment by Gutz-Pilz** [comment]
i dont like that intonation. Please be kind!
those guys dont get paid for doing all this!

I appreciate all your work and love to enhance pyload with my own hooks.

**Comment by vuolter** [comment]
@venious No, but I'm working hard to fix all reported bugs.
