### ISSUE TITLE
file name problem with Real Debrid plugin

### ISSUE THREAD

**Issue by Dybala93** [pyload/pyload#1661]
I don't know why in the last month ever problems with pyload...I must reinstall it? for the last problems I thanks vuolter for support but resolved with auto-update... I think! (when I reported the issue no update were available)
Now this new problem: all my links becomes for ex.: from "1.rar" to "zfjagjawg"
On log the problem is this:

HOSTER RealdebridCom[267]: RealdebridCom | Updating file info...

That transform file name.
Thanks again for help and sorry for my english!

**Comment by Dybala93** [comment]
News?

**Comment by macross5** [comment]
same problem here.

**Comment by macross5** [comment]
Here is my log file. I renamed direct names to X. 
As you see, RealdebridCom seems to havent rights to work in my download folder. I didnt changed the permissions and i granted it to the pyload user-group.

Maybe the issue is there, that Realdebrid didnt got the zipname of the file or he got it, but still cant change it cause of a bad "execute rename" command?

Just write to me, if i can help.

> DEBUG	HOSTER RealdebridCom[1567]: RealdebridCom | LOAD URL http://uploaded.net/file/X | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
INFO	HOSTER RealdebridCom[1567]: RealdebridCom | File status: queued
INFO	HOSTER RealdebridCom[1567]: RealdebridCom | Processing as premium download...
DEBUG	HOSTER RealdebridCom[1567]: RealdebridCom | LOAD URL https://real-debrid.com/ajax/unrestrict.php | cookies=True | get={'lang': 'en', 'password': '', 'link': u'http://uploaded.net/file/X', 'time': 1439182807716L} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG	HOSTER RealdebridCom[1567]: RealdebridCom | Returned Data: {u'main_link': u'http://de.rdeb.io/d/X/X.rar', u'media_keys': False, u'file_name': u'X.rar', u'error': 0, u'hoster_image': u'ul.png', u'max_chunks': u'-1', u'file_size_bytes': u'X', u'link': u'http://uploaded.net/file/X', u'swap': False, u'file_size': u'XMB', u'hoster_name': u'Uploaded', u'generated_links': [[u'X.rar', u'', u'http://de.rdeb.io/d/X/X.rar']], u'hoster_url': u'uploaded.to,uploaded.net,ul.to'}
INFO	HOSTER RealdebridCom[1567]: RealdebridCom | Downloading file...
DEBUG	HOSTER RealdebridCom[1567]: RealdebridCom | DOWNLOAD URL http://de.rdeb.io/d/X/X.rar | cookies=True | get={} | disposition=True | post={} | ref=True
WARNING	HOSTER RealdebridCom[1567]: RealdebridCom | Setting path mode failed | [Errno 1] Operation not permitted: '/X/'

**Comment by GammaC0de** [comment]
I think this can be closed.
If not, please specify here and I will reopen.
