### ISSUE TITLE
OboomCom - Premium not working - premium: None

### ISSUE THREAD

**Issue by fekoh** [pyload/pyload#1799]
Pyload 0.4.9 stable - fresh install

in pyload it says i have no Premium at OboomCom. But if i login with the same account information to oboom.com i have premium.

Also 'trafficleft' and 'validuntil' are set to 'None'.

Output of debug:

30.08.2015 16:20:58 DEBUG     ACCOUNT OboomCom: LOAD URL http://www.oboom.com/1/login | cookies=True | get={'auth': 'xxx', 'pass': 'yyy'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
30.08.2015 16:20:58 INFO      ACCOUNT OboomCom: Parsing account info for user `xxx`...
30.08.2015 16:20:58 DEBUG     ACCOUNT OboomCom: Account info for user `xxx`: {'login': {'timestamp': 1440946916.7015, 'password': '*********_', 'valid': True}, 'data': {'premium': None, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': 'xxx', 'password': '**_*******', 'type': 'OboomCom', 'valid': True}}

**Comment by joberreiter** [comment]
As far as I remember from previous issues: You may check accounts.conf if the password is correct.

**Comment by FeGitHub** [comment]
I checked accounts.conf - username and password are correct.

**Comment by boerngen-schmidt** [comment]
@FeGitHub just for interest, try starting pyload from the commandline with the debug option on and check if the accounts work

**Comment by FeGitHub** [comment]
Still no premium, even in debug. The output of my first post is from debug:

30.08.2015 16:20:58 DEBUG ACCOUNT OboomCom: Account info for user xxx: {'login': {'timestamp': 1440946916.7015, 'password': '*******', 'valid': True}, 'data': {'premium': None, 'trafficleft': None, 'options': {}, 'maxtraffic': None, 'validuntil': None, 'login': 'xxx', 'password': '*******', 'type': 'OboomCom', 'valid': True}}

**Comment by FeGitHub** [comment]
Anyone using a working OboomCom account? Can't imagine that i'm the only one with this problem.

**Comment by FeGitHub** [comment]
![oboom](https://cloud.githubusercontent.com/assets/13085282/9617406/280b7fa4-5102-11e5-9fba-3991dd509d60.png)
![pyload](https://cloud.githubusercontent.com/assets/13085282/9617405/280a9a26-5102-11e5-9ee2-26f2f9fd919a.png)

**Comment by boerngen-schmidt** [comment]
@FeGitHub could you clone the pyload stable branch and try this one? I guess the problem is located in the response from oboom and the processing of this information by pyload. see #1545 where the scheme was changed from https to http. Maybe that is the source of your problem now.

But I'm a nice guy and looked around in the code and the API of oboom. The Oboom response stated here: https://www.oboom.com/api/1/login does not have an attribute called premium and pyload https://github.com/pyload/pyload/blob/stable/module/plugins/accounts/OboomCom.py#L55 seems to check for this attribute to say wether U got a premiumaccount or not.

@vuolter hope this enough information for a quick fix. Also https seems to be working again.

**Comment by FeGitHub** [comment]
Thanks for your help -I really appreciate it!
All my posts are based on the github stable branch.
