### ISSUE TITLE
untested changes in stable branch

### ISSUE THREAD

**Issue by nordic-style** [pyload/pyload#1837]
Would it be possible that you don't commit untested code into the stable branch? In the last 6 month or so this broke pyload like 3 times for days. I don't have any problems to test a special branch. If you need machines for a testing setup or just for a test deployment i can support you with these.

Cheers and keep the good work up!

**Comment by stangri** [comment]
Since there's no star or like button, I'm replying to show my support of this idea.

**Comment by Gutz-Pilz** [comment]
Yes. This was mentioned before.
But still a good idea :)

**Comment by janpal** [comment]
:+1:  I wrote exactly the same comment couple of weeks ago. 
Now there is another cross plugin issue. I am ok with testing but i also need stable version in parallel. You are really ruining this project with this approach :-(

**Comment by joberreiter** [comment]
+1

**Comment by nRaecheR** [comment]
I totally agree to that. The 'stable' tree is broken till weeks and @voulter continues to push utterly untested code on a daily basis. 

The current 'stable' version doesn't even start to download anything and some hosters are broken since days (Rapidgator, UploadedCH, TurboBit etc. etc.). Currently I fear every update made to the project. 
The project really needs some kind of QA. New code should be tested on a different branch and should be pulled to 'stable' after tested successfully there. What about some automatic tests ? Or at least, @voulter, run and test your changes *before* you commit it in the 'stable' branch...the stable branch doesn't deserve it's name lately.

**Comment by Velociraptor85** [comment]
@GammaC0de as far as I understand the stable branch is stable again although its not the default branch I guess we can close this issue for now?

**Comment by GammaC0de** [comment]
All those issues are gone now.
pyload is stable.
