### ISSUE TITLE
LinkCrypt.ws using CloudFlare Ddos protection results in an 503

### ISSUE THREAD

**Issue by ghost** [pyload/pyload#1872]
LinkCrypt.ws is using cloudflare with it's ddos protection, which checks your browser with javascript and redirects you. Requests from scripts and commandlinetools will fail because they are not using the generated cookie. Pyload will result in an 503-error.

**Comment by GammaC0de** [comment]
I also seen it used in another hoster (I think UpleaCom)

**Comment by Bambie42** [comment]
i had a look into the "protection". It redirects to a site that has two keys, another one will be generated using javascript (my problem at the moment). Than this three keys are sent to an url, which validates your cookies to use the domain for a period of time.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/f0c49a8db0671219e6e2e225880488cb71bafa90 Created new hook plugin [CloudFlareDdos](https://github.com/pyload/pyload/blob/f0c49a8db0671219e6e2e225880488cb71bafa90/module/plugins/hooks/CloudFlareDdos.py) (not active by default)
Currently supports only `SimpleHoster` based plugins.

Reuires a patched [HTTPRequest.py](https://github.com/GammaC0de/pyload/blob/1f8acaefb33faacbe85fc00ae961f1ab7ae6e8e8/pyload/network/HTTPRequest.py) to resolve https://github.com/pyload/pyload/issues/2565

Unfortunately,
I could not test the ddos challenge because I could not find a site with it.

**Comment by GammaC0de** [comment]
CloudFlareDdos should work by now.
