### ISSUE TITLE
Download failed: XXXXXXXXXXXXX | No plugin matched 

### ISSUE THREAD

**Issue by XneddyX** [pyload/pyload#1969]
Hello...

At this time i have the following problem...

32	07.10.2015 17:59:22	INFO	Download starts: XXXXXXXX
33	07.10.2015 17:59:22	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
34	07.10.2015 17:59:22	DEBUG	HOSTER BasePlugin[1009]: Config option `use_premium` not found, use default `True`
35	07.10.2015 17:59:22	DEBUG	HOSTER BasePlugin[1009]: PROCESS URL ://http://share-online.biz/dl/XXXXXXXXXX| PLUGIN VERSION 0.46
36	07.10.2015 17:59:22	DEBUG	HOSTER BasePlugin[1009]: Config option `fallback_premium` not found, use default `True`
37	07.10.2015 17:59:22	WARNING	Download failed: XXXXXXXXX | No plugin matched
38	07.10.2015 17:59:22	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: XXXXXXXXXXX (pid:23)
39	07.10.2015 17:59:22	INFO	ADDON UnSkipOnFail: No duplicates found
40	07.10.2015 17:59:24	DEBUG	HOSTER BasePlugin[1010]: Config option `use_premium` not found, use default `True` 
![queue](https://cloud.githubusercontent.com/assets/14812051/10343389/e379d380-6d1d-11e5-99cf-7c13588f0da7.jpg)

**Comment by maelue** [comment]
The same error here :-(

**Comment by Arno-Nymous** [comment]
The same goes for me. See attached some debug log output.
What really looks odd is that the BasePlugin tries to process URLs with a pattern of `://http://share-online.biz/...`. I think it chokes on the `://` at the beginning which definitely is not supposed to be there ;)

I added some more lines to my debug log snippet showing that the DLC plugin incorrectly parses the DLC container and passes those links with the starting `://`. Since in this case the BasePlugin only sees links starting with `://` instead of `http://` it nags 'No plugin matched'.

If you need some more info, just yell ;)

P.S.: Sorry for posting the log inline but github won't upload my file for some reason as stated by some other folks before already. So, here it comes...


07.10.2015 11:12:53 INFO      Download starts: XXXXXXXXXX
07.10.2015 11:12:53 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
07.10.2015 11:12:53 DEBUG     HOSTER BasePlugin[28]: Config option `use_premium` not found, use default `True`
07.10.2015 11:12:53 DEBUG     HOSTER BasePlugin[28]: PROCESS URL ://http://www.share-online.biz/dl/XXXXXXXXXX | PLUGIN VERSION 0.46
07.10.2015 11:12:53 DEBUG     HOSTER BasePlugin[28]: Config option `fallback_premium` not found, use default `True`
07.10.2015 11:12:53 WARNING   Download failed: XXXXXXXXXX | No plugin matched
07.10.2015 11:12:53 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: XXXXXXXXXX (pid:4)
07.10.2015 11:12:53 INFO      ADDON UnSkipOnFail: No duplicates found
07.10.2015 11:12:55 DEBUG     HOSTER BasePlugin[29]: Config option `use_premium` not found, use default `True`
07.10.2015 11:12:55 INFO      Download starts: XXXXXXXXXX
07.10.2015 11:12:55 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
07.10.2015 11:12:55 DEBUG     HOSTER BasePlugin[29]: Config option `use_premium` not found, use default `True`
07.10.2015 11:12:55 DEBUG     HOSTER BasePlugin[29]: PROCESS URL ://http://www.share-online.biz/dl/XXXXXXXXXX | PLUGIN VERSION 0.46
07.10.2015 11:12:55 DEBUG     HOSTER BasePlugin[29]: Config option `fallback_premium` not found, use default `True`
07.10.2015 11:12:55 WARNING   Download failed: XXXXXXXXXX | No plugin matched
07.10.2015 11:12:55 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: XXXXXXXXXX (pid:4)
07.10.2015 11:12:55 INFO      ADDON UnSkipOnFail: No duplicates found
07.10.2015 11:12:57 ERROR     ADDON ClickAndLoad: [Errno 98] Address already in use
07.10.2015 11:12:57 DEBUG     HOSTER BasePlugin[30]: Config option `use_premium` not found, use default `True`
07.10.2015 11:12:57 INFO      Download starts: XXXXXXXXXX
07.10.2015 11:12:57 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
07.10.2015 11:12:57 DEBUG     HOSTER BasePlugin[30]: Config option `use_premium` not found, use default `True`
07.10.2015 11:12:57 DEBUG     HOSTER BasePlugin[30]: PROCESS URL ://http://www.share-online.biz/dl/XXXXXXXXXX | PLUGIN VERSION 0.46
07.10.2015 11:12:57 DEBUG     HOSTER BasePlugin[30]: Config option `fallback_premium` not found, use default `True`
07.10.2015 11:12:57 WARNING   Download failed: XXXXXXXXXX | No plugin matched
07.10.2015 11:12:57 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: XXXXXXXXXX (pid:4)
07.10.2015 11:12:57 INFO      ADDON UnSkipOnFail: No duplicates found

[...]

07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: Config option `use_premium` not found, use default `True`
07.10.2015 11:44:57 INFO      Decrypting starts: /path/to/dlc/tmp_16eaCNq118.dlc
07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: Config option `use_premium` not found, use default `True`
07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: PROCESS URL /path/to/dlc/tmp_16eaCNq118.dlc | PLUGIN VERSION 0.26
07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: LOAD URL http://service.jdownloader.org/dlcrypt/service.php?srcType=dlc&destType=pylo&data=Nm5oZGdLV0tkUXJPU2lqOUR5RElTWWx5S3hQZkwvTFd2RXMzYnlXODBvRUpkc25qZ3pYQXkreTdLaEtjd044bA== | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: Config option `use_subfolder` not found, use default `True`
07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: Config option `subfolder_per_package` not found, use default `True`
07.10.2015 11:44:57 INFO      CONTAINER DLC[31]: Parsed package: Paket 0 | Found 18 links | Saved to folder: Paket 0
07.10.2015 11:44:57 DEBUG     CONTAINER DLC[31]: LINKS for package Paket 0 | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX | ://http://www.share-online.biz/dl/XXXXXXXXXX
07.10.2015 11:44:57 DEBUG     Run Info Fetching for BasePlugin
07.10.2015 11:44:57 INFO      Added package Paket 0 containing 18 links

**Comment by R3alflash** [comment]
same here:

209	08.10.2015 13:25:36	DEBUG	ACCOUNT ShareonlineBiz: Account info for user `xxxxx`: {'login': {'timestamp': 1444303513.1540999, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1444751791.0, 'trafficleft': 104711181.890625, 'maxtraffic': 104857600L, 'premium': True, 'options': {'limitdl': ['0']}}}
210	08.10.2015 13:28:31	DEBUG	HOSTER BasePlugin[161]: Config option `use_premium` not found, use default `True`
211	08.10.2015 13:28:31	INFO	Download starts: xxxxxx
212	08.10.2015 13:28:31	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
213	08.10.2015 13:28:31	DEBUG	HOSTER BasePlugin[161]: Config option `use_premium` not found, use default `True`
214	08.10.2015 13:28:31	DEBUG	HOSTER BasePlugin[161]: PROCESS URL ://http://www.share-online.biz/dl/xxxxxxxx | PLUGIN VERSION 0.46
215	08.10.2015 13:28:31	DEBUG	HOSTER BasePlugin[161]: Config option `fallback_premium` not found, use default `True`
216	08.10.2015 13:28:31	WARNING	Download failed: 93T6ITVNPWO | No plugin matched
217	08.10.2015 13:28:31	DEBUG	All downloads processed

**Comment by vuolter** [comment]
Side effect of https://github.com/pyload/pyload/pull/1964.
