### ISSUE TITLE
problems with ClickNLoad

### ISSUE THREAD

**Issue by GammaC0de** [pyload/pyload#1991]
Hi,
After the rename of `ClickAndLoad.py` to `ClickNLoad.py` I started to get `error: (98, 'Address already in use')` errors.

I was thinking, *"Of-course - this is because of there are now two plugins: `ClickAndLoad` and `ClickNLoad`"*
So I issued #1955 thinking that it would solve the problem.

After waiting for 5 days for https://github.com/pyload/updatemanager/pull/29 to be merged, I gave up and deleted  `ClickAndLoad.py` by hand, thinking that it would solve my problems.

Surprisingly I was wrong: I continued getting `error: (98, 'Address already in use')`
I said: *"No way! that can`t be! I have just deleted the duplicate plugin!"*

After few hours of research and hair-pulling, I found that there is another `ClickAndLoad.py` in `/share/pyload/module/plugins/hooks` (v0.2) that comes with the core of `pyLoad 0.4.9` release and is activated by default so that makes the conflict.

So, to override the old `ClickAndLoad` plugin, you have to rename `ClickNLoad.py` back to `ClickAndLoad.py`

Also, for me, `ClickAndLoad` is much more pleasant to the eye.

**Comment by joberreiter** [comment]
Yes, there are always 2 possible plugin locations, `<config directory>/userplugins` and `<pyload directory>/modules/plugins`.
I think this is due to the fact that pyload has not always write permission in its own directory, but the updater need a place to store updated plugins.
This is also the reason for log entries of the form (for instance)
```14.06.2015 16:39:52 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
```
Changing a plugins name has the side-effect that if you delete only one of the two locations, it 'doubles' this plugin (old version at the second location, new version coming through the updater), so you are experiencing exactly the problem you described.

> So, to override the old ClickAndLoad plugin, you have to rename ClickNLoad.py back to ClickAndLoad.py
No, just delete it at both locations--should be enough (was for me).

But if it has been blacklisted, this sould work (not heard of an issue with that)--but I know pyLoad to less whats happening when doing plugin blacklisting (only ignore the plugin when registering plugins or physically delete it? If pyLoad has no write permission in its own directory, I assume the former). But I think vuolter can clarify this if needed.

> Also, for me, ClickAndLoad is much more pleasant to the eye.

It's 'officially' Click'n'Load, not 'Click and Load', so I can understand vuolter at this point (but it is a good example what cosmetic changes can do, if they are committed untested -- and this seems to be a simple renaming, no change of the underlying code base).

**Comment by GammaC0de** [comment]
After some more research I can say that UpdateManager will delete any blacklisted plugin from `<config directory>/userplugins` and `<pyload directory>/modules/plugins` (if it has the permission to do that)

so @vuolter please merge https://github.com/pyload/updatemanager/pull/29!
