### ISSUE TITLE
Issue with Debriditalia plugin 

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#1993]
Hello
after the premium accounts of Alldebrid, Uptobox : now the Debriditilia plugin does not work anymore.

**Comment by cedmeister** [comment]
Same for me...

**Comment by damien599901** [comment]
Same status 10 days later :(

**Comment by vuolter** [comment]
MultiAccount is 90% done.

**Comment by Alestrix** [comment]
What's the status of this issue? DebritITalia Plugin still not working with stable release and the "90% done" statement is almost a year old by now. pyLoad is of no use for many if MultiHosters don't work.

On a side note, if an issue is marked as duplicate, please add a reference to the issue this issue is a duplicate of. All issues I have found about this topic are all marked duplicate, but there is no "master" issue that I could put on my watchlist.
Is there an older version of pyLoad with working DebridItalia Plugin?

**Comment by damien599901** [comment]
+ 1 for the older version for alldebrid

**Comment by oechslein** [comment]
I think this is the duplicate to all the multi hoster issues: #2121
