### ISSUE TITLE
PremiumizeMe does not work

### ISSUE THREAD

**Issue by MaxPower88** [pyload/pyload#2109]
A couple of days ago the problems seemed to be fixed and it worked again, but now it seems pyload doesn't use my PremiumizeMe account to download from supported hosters. Instead it tries to use the respective Hoster plugins (i.e. Rapidgator or Uploaded for example). Debug logs don't show anything, except that it uses 

INFO    HOSTER UploadedTo[127]: Grabbing link info...

instead of PremiumizeMe.

And something about OldPremiumizeMe:

ERROR   Error executing hooks: 'module' object has no attribute 'OldPremiumizeMe'

**Comment by ploebb** [comment]
Yep. Can confirm this behavior. Disabling the Uploded-Plugin has no effect.

Dirty workaround:
- disable update-manager
- delete Uploaded-plugin-file
- use __pattern__ from uploaded-plugin-file in premiumize-plugin-file

**Comment by Messenger6** [comment]
Hello all, can someone concrete explain what to do?
- delete Uploaded-plugin-file
under folder accounts?

- use pattern from uploaded-plugin-file in premiumize-plugin-file
which pattern exactcly to which position?

**Comment by ploebb** [comment]
> under folder accounts?

No. In the install-folder "(usr/share/)pyload/modules/plugins/hosters
Delete <code>UploadedTo.py</code> and <code>UploadedTo.pyc</code>
The install folder may vary.
Also check the <code>userplugins</code> folder in your pyload-config-directory. (default: <code>~/.pyload/userplugins/hoster</code>)

> which pattern exactcly to which position?

there is a variable <code>__ pattern __ </code> in each hoster-plugin-file which should match any download-link of this hoster. So you have to change the pattern in the <code>PremiumizeMe.py</code> file to the one in the <code>UploadedTo.py</code> file.

But I noticed there were a lot of duplicate-tags added to issues lately. I guess it's a problem with all the multihosters and gets resolved soon.

Thanks in advance to the developers for your work :-)

**Comment by Messenger6** [comment]
Thank you for your answer.

**Comment by cavebeat** [comment]
:imp: i am also facing this problem
i reinstalled pyLoad on a new Debian Jessie box. 
and it fails to work :( 

for the updates i had to follow https://github.com/pyload/pyload/issues/1553 and now it fails to download from premiumize.me

also i cannot disable premiumize.me and enable a different account.

**Comment by LeifuXP** [comment]
I have the same Problem, pleeaasse help !

**Comment by hchanb** [comment]
yeah, same here!!!

**Comment by LeifuXP** [comment]
does anyone know a workaround ? the dirty workaround from ploebb doesnt work

**Comment by realwax** [comment]
Premiumize.me plugin is dead since some time. I got in touch with them. They told me they did not change the API since some time. so +1 from my side. 
Vuolter can you please have a look? Thank you very much!

**Comment by LeifuXP** [comment]
anything new about this problem ???

**Comment by boerngen-schmidt** [comment]
@LeifuXP if there would be anything new, the ticket would have been updated. It is as it is.

**Comment by MaxPower88** [comment]
Since there haven't been any commits since about two weeks I doubt anything has changed. Voulter is probably busy atm.

**Comment by oxi** [comment]
Workaround working only with Premiumize.Me:
Edit module/PyFile.py:
    Before line 101 add: 
        self.pluginname = "PremiumizeMe"

Edit module/plugins/hoster/PremiumizeMe.py:
    Replace line 52 with: 
        self.pyfile.name = pyfile.name
    Replace line 55 with: 
        self.pyfile.size = 100

    This I made, because the API from PremiumizeMe doesn't show the Size and the Name any more :/

**Comment by maxnowack** [comment]
any updates on this issue?

**Comment by gregorriegler** [comment]
+1

**Comment by vuolter** [comment]
See: https://github.com/pyload/pyload/issues/2121

**Comment by steilerDev** [comment]
Hey guys, since the functionality isn't available yet, but I really need to download DLC's onto my headless server, [I created a very simple bash script for downloading uploaded.to files from a DLC using premiumize.me](https://github.com/steilerDev/premiumize.me-cli-downloader) . Maybe this helps until we can all use pyload for this kind of use case again.

**Comment by exislow** [comment]
Will it be fixed?

**Comment by GammaC0de** [comment]
Sure it will, the question is when.

**Comment by exislow** [comment]
Hopefully soon?

**Comment by GammaC0de** [comment]
Hopefully,
I am currently in the middle of trying to.

**Comment by MaxPower88** [comment]
Really? Awesome. I was about to write something cynical ^^

**Comment by GammaC0de** [comment]
Its today!!  :birthday: :birthday: :birthday:

https://github.com/pyload/pyload/commit/a4eec2b6e6014d33025ac36b83d60a73ff9d99c1
Please update if it works for you.

**Comment by MaxPower88** [comment]
Do we need to manually update that one file, or is the update manager still working?

**Comment by GammaC0de** [comment]
Its working unless your have issues 
 
  On יום ה׳, פבר׳ 2, 2017 at 4:23, MaxPower88<notifications@github.com> wrote:   
Do we need to manually update that one file, or is the update manager still working?

**Comment by MaxPower88** [comment]
Hmm, well, at first it didn't show me anything. Now after multiple restarts and restarting the UpdateManager module it shows me "New pyload" and to get it from git/releases. 

Maybe I am misunderstanding something, but last I used pyload the updatemanager updated pyload automatically? Did that change, or is something broken with my install?

**Comment by GammaC0de** [comment]
Your update manager is jammed. Please delete your userplugins directly and reaplace updatemnager.py according to the instructions In #2000

 
 
  MaxPower88<notifications@github.com> wrote:   
Hmm, well, at first it didn't show me anything. Now after multiple restarts and restarting the UpdateManager module it shows me "New pyload" and to get it from git/releases.

Maybe I am misunderstanding something, but last I used pyload the updatemanager updated pyload automatically? Did that change, or is something broken with my install?

**Comment by MaxPower88** [comment]
Found the issue, old updatemanager.pyload.org url was still in updatemanager hook. Replaced it, now its updating.

**Comment by MaxPower88** [comment]
AWESOME MAN! Thank you so much, it works :D 

I got some error in the logs

02.02.2017 03:51:29	ERROR	ACCOUNT PremiumizeMe: Error performing periodical task | 'data'

Not sure if that's relevant. It does download like a charm, so ^^

**Comment by GammaC0de** [comment]
That's great news:) 
Canon you start pyload from the console (python pyLoadCore.py - d)  and see of there is exception information? 
 

MaxPower88<notifications@github.com> wrote:   
AWESOME MAN! Thank you so much, it works :D

I got some error in the logs

02.02.2017 03:51:29 ERROR ACCOUNT PremiumizeMe: Error performing periodical task | 'data'

Not sure if that's relevant. It does download like a charm, so ^^

**Comment by MaxPower88** [comment]
```
02.02.2017 04:07:40 ERROR     ACCOUNT PremiumizeMe: Error performing periodical task | 'data'
Traceback (most recent call last):
  File "/opt/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/max/.pyload/userplugins/internal/misc.py", line 181, in _task
    self.task()
  File "/home/max/.pyload/userplugins/internal/MultiAccount.py", line 127, in periodical_task
    if not self.info['data'].get('hosters'):
KeyError: 'data'
```

**Comment by exislow** [comment]
Now PremiumizeMe seems to work, at least it retrieves the correct Account Information (valid, status, traffic). But I can't download files, for instance, from ul.to. PyLoad asks for a captcha. What is wrong?

```
622	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: Previous link info: {'status': 2, 'url': u'http://uploaded.net/file/xxx', 'size': 7728694, 'name': 'xxx.zip', 'pattern': {'ID': u'xxx'}}
623	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Link name: xxx.zip
624	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Link size: 7.37 MiB (7728694 bytes)
625	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Link status: online
626	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Looking for direct download link...
627	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: Redirect #0 to: http://uploaded.net/file/xxx
628	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/file/xxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
629	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Direct download link not found
630	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/file/nza8sbmy | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
631	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Processing as free download...
632	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/language/en | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
633	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/js/download.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
634	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
635	02.02.2017 09:44:24	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://www.google.com/recaptcha/api/challenge | redirect=True | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
636	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | Challenge: 03AHJ_Vuv5--ZokN1tvVr9SkZae07wXOrrisNZgUdFTAjfkU38QrUXDEf32UyCK-_HX0KjyfaAwePpxs5Xq3kHZ46tGHAndPExTiV9sCUqdwzBGM_7yQ9uE4xQC9ta5g0TPMvYOUergIZBV5ABLUfliYeRpI_WyOAQcoszPv49qIbtF2WvlOCJ1lwZCHGaBwP0Ey6gvN2hQ5n2lqZ-3x-gpWyXwB_LWFWz-A
637	02.02.2017 09:44:24	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
638	02.02.2017 09:44:24	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://www.google.com/recaptcha/api/reload | redirect=True | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vuv5--ZokN1tvVr9SkZae07wXOrrisNZgUdFTAjfkU38QrUXDEf32UyCK-_HX0KjyfaAwePpxs5Xq3kHZ46tGHAndPExTiV9sCUqdwzBGM_7yQ9uE4xQC9ta5g0TPMvYOUergIZBV5ABLUfliYeRpI_WyOAQcoszPv49qIbtF2WvlOCJ1lwZCHGaBwP0Ey6gvN2hQ5n2lqZ-3x-gpWyXwB_LWFWz-A', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
639	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | Second challenge: 03AHJ_VuskIz4jYk_26tTvXZTNEyg_6rkTvaB1ybCJxLHuRRICg_nXtCPo6FlBGkLH6NbXUhJlueOPDjcNrmkwXuawgjINE8gxWSOC5qBWiHCa67HWckOpCVeEsNiuHIBU_kvJgKPHqOljkt9ZmAPZ7JfY7_jCu9Y5BWL-p6vgTH40tb8sQYRKtVNin7Vemksv2Vy4xINHx06r
640	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | redirect=True | cookies=True | get={'c': u'03AHJ_VuskIz4jYk_26tTvXZTNEyg_6rkTvaB1ybCJxLHuRRICg_nXtCPo6FlBGkLH6NbXUhJlueOPDjcNrmkwXuawgjINE8gxWSOC5qBWiHCa67HWckOpCVeEsNiuHIBU_kvJgKPHqOljkt9ZmAPZ7JfY7_jCu9Y5BWL-p6vgTH40tb8sQYRKtVNin7Vemksv2Vy4xINHx06r'} | req= | decode=False | multipart=False | post={} | ref=False | just_header=False
641	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | This function does nothing
```

**Comment by GammaC0de** [comment]
@exislow what plugin version are you using? Its seems that you have not got the update because the download is still handled by the plugin and not  PremiumizeMe. 




exislow<notifications@github.com> wrote:   
Now PremiumizeMe seems to work, at least it retrieves the correct Account Information (valid, status, traffic). But I can't download files, for instance, from ul.to. PyLoad asks for a captcha. What is wrong?
622	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: Previous link info: {'status': 2, 'url': u'http://uploaded.net/file/xxx', 'size': 7728694, 'name': 'xxx.zip', 'pattern': {'ID': u'xxx'}}
623	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Link name: xxx.zip
624	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Link size: 7.37 MiB (7728694 bytes)
625	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Link status: online
626	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Looking for direct download link...
627	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: Redirect #0 to: http://uploaded.net/file/xxx
628	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/file/xxx | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
629	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Direct download link not found
630	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/file/nza8sbmy | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
631	02.02.2017 09:44:23	INFO	HOSTER UploadedTo[86]: Processing as free download...
632	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/language/en | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
633	02.02.2017 09:44:23	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://uploaded.net/js/download.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
634	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
635	02.02.2017 09:44:24	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://www.google.com/recaptcha/api/challenge | redirect=True | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
636	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | Challenge: 03AHJ_Vuv5--ZokN1tvVr9SkZae07wXOrrisNZgUdFTAjfkU38QrUXDEf32UyCK-_HX0KjyfaAwePpxs5Xq3kHZ46tGHAndPExTiV9sCUqdwzBGM_7yQ9uE4xQC9ta5g0TPMvYOUergIZBV5ABLUfliYeRpI_WyOAQcoszPv49qIbtF2WvlOCJ1lwZCHGaBwP0Ey6gvN2hQ5n2lqZ-3x-gpWyXwB_LWFWz-A
637	02.02.2017 09:44:24	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
638	02.02.2017 09:44:24	DEBUG	HOSTER UploadedTo[86]: LOAD URL http://www.google.com/recaptcha/api/reload | redirect=True | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vuv5--ZokN1tvVr9SkZae07wXOrrisNZgUdFTAjfkU38QrUXDEf32UyCK-_HX0KjyfaAwePpxs5Xq3kHZ46tGHAndPExTiV9sCUqdwzBGM_7yQ9uE4xQC9ta5g0TPMvYOUergIZBV5ABLUfliYeRpI_WyOAQcoszPv49qIbtF2WvlOCJ1lwZCHGaBwP0Ey6gvN2hQ5n2lqZ-3x-gpWyXwB_LWFWz-A', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
639	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | Second challenge: 03AHJ_VuskIz4jYk_26tTvXZTNEyg_6rkTvaB1ybCJxLHuRRICg_nXtCPo6FlBGkLH6NbXUhJlueOPDjcNrmkwXuawgjINE8gxWSOC5qBWiHCa67HWckOpCVeEsNiuHIBU_kvJgKPHqOljkt9ZmAPZ7JfY7_jCu9Y5BWL-p6vgTH40tb8sQYRKtVNin7Vemksv2Vy4xINHx06r
640	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | redirect=True | cookies=True | get={'c': u'03AHJ_VuskIz4jYk_26tTvXZTNEyg_6rkTvaB1ybCJxLHuRRICg_nXtCPo6FlBGkLH6NbXUhJlueOPDjcNrmkwXuawgjINE8gxWSOC5qBWiHCa67HWckOpCVeEsNiuHIBU_kvJgKPHqOljkt9ZmAPZ7JfY7_jCu9Y5BWL-p6vgTH40tb8sQYRKtVNin7Vemksv2Vy4xINHx06r'} | req= | decode=False | multipart=False | post={} | ref=False | just_header=False
641	02.02.2017 09:44:24	DEBUG	CAPTCHA UploadedTo[86]: ReCaptcha | This function does nothing

**Comment by exislow** [comment]
You are right. PremiumizeMe Plugin is still 0.20. Strange... I have restarted pyLoad twice. Update should be there.

**Comment by exislow** [comment]
I just cloned the whole plugins dir. Now it works! Great work. Thank you so much.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/issues/2109#issuecomment-276853117

 
 
  exislow<notifications@github.com> wrote:   
I just cloned the whole plugins dir. Now it works! Great work. Thank you so much.

**Comment by GammaC0de** [comment]
👍

**Comment by exislow** [comment]
This plugin is unfortunately not stable at all. I get a lot of these errors:

```
12.02.2017 22:08:50	WARNING	HOSTER PremiumizeMe[211]: PremiumizeMe | Plugin may be unstable
985	12.02.2017 22:08:50	INFO	ACCOUNT PremiumizeMe: Grabbing account info for user `X`...
986	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Grabbing link info...
987	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Link name: Y.part072.rar
988	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Link size: 168.00 B (168 bytes)
989	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Link status: starting
990	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Processing url: http://uploaded.net/file/Z/Y.part072.rar
991	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Checking for link errors...
992	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | No errors found
993	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Grabbing link info...
994	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Link name: Y.part072.rar
995	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Link size: 168.00 B (168 bytes)
996	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Link status: starting
997	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Processing as premium download...
998	12.02.2017 22:08:50	INFO	ACCOUNT PremiumizeMe: Grabbing account info for user `X`...
999	12.02.2017 22:08:50	INFO	HOSTER PremiumizeMe[211]: PremiumizeMe | Downloading file...
```

See the byte size (```168.00 B (168 bytes```)? It is wrong. In the UI there is a ```403 Forbidden``` error. And the downloaded file named ```Y.part072.rar.chunk0``` has the following content:

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

Do you know why this happens? JDownloader works fine on this (and other=) files.

**Comment by GammaC0de** [comment]
@exislow Please open a new issue, thanks.
