### ISSUE TITLE
Replace PycURL with Requests to allow PyPy porting

### ISSUE THREAD

**Issue by vuolter** [pyload/pyload#2184]

**Comment by lukastribus** [comment]
@vuolter @GammaC0de as mentioned in #3250, requests instead of pycurl would be great for a number of reasons (pure python dependency, no gnutls issues), however not at the cost of a huge overhead/slower speeds.

A few points:

- Is it really that bad (probably, I don't know)?
- could we support both based on availability (just like with other libraries, but probably too much hassle)?
- could we limit pycurl just to performance critical paths/downloading (probably too much hassle as well)?
- in a hypothetical requests based pyload, could we use basic urllib instead of pycurl for performance critical paths (if basic urllib is comparably performant than pycurl for bulk downloads)?

I'm not suggesting any of this, just floating random thoughts.


The reason pycurl is linked to GnuTLS in Debian/Ubuntu are licensing issues. The [next major OpenSSL release](https://www.openssl.org/source/license.html) will switch to the Apache license, probably fixing that licensing issue, so it is possible that some point in future Debian/Ubuntu will switch to a OpenSSL based pycurl (but probably not within the next 5 years).


I guess some benchmarking is required between pycurl, urllib, urllib3 and requests - specifically regarding bulk download performance and it's CPU overhead.

**Comment by lukastribus** [comment]
Note: Debian since 13 / Trixie and Ubuntu since 24.10 / Oracular are linking pycurl against OpenSSL instead of GnuTLS, resolving GnuTLS based SSL issues (although I'm not sure this is even relevant for recent GnuTLS versions anymore).

**Comment by GammaC0de** [comment]
All those issues are irrelevant nowadays, closing.
