### ISSUE TITLE
RealDebrid and AllDebrid not working (only tries to download as free user from the actual hoster, eg UploadedTo)

### ISSUE THREAD

**Issue by salimimani** [pyload/pyload#2278]
Hello, here's my issue :
- Fresh installation of pyload
- RealDebrid account configured (it is first shown as "premium : NO" and when I stop and restart pyload it is succesfully configured as "premium : YES")
- Nothing changed in settings

When I try to start a download, it doesn't use my RealDebrid account and downloads directly from the hoster : "Processing as free download"
I have tried deleting my .pyload folder, reinstalling from scratch, but nothing helps

I also noticed there used to be a "RealDebridCom Hook" section in the settings, but it doesn't exist anymore.
Note that I also tried with AlldebridCom, with a premium account, and it behaves the same way, totally ignoring the plugin and downloading with the hoster (UploadedTo, OneFichierCom, ...)
I can't find any setting to enable/disable RealDebrid so I can't figure out how to make it work

403 09.01.2016 22:04:41 INFO    Download starts: _Da.Vincis.Demons.S03E01.FASTSUB.VOSTFR.720p.HDTV.x264-SAMIR31.mkv
404 09.01.2016 22:04:42 WARNING HOSTER UploadedTo[6]: Plugin may be unstable
405 09.01.2016 22:04:42 INFO    HOSTER UploadedTo[6]: Grabbing link info...
406 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Link name: _Da.Vincis.Demons.S03E01.FASTSUB.VOSTFR.720p.HDTV.x264-SAMIR31.mkv
407 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Link size: 1.05 GiB (1122688523 bytes)
408 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Link status: online
409 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Processing url: http://uploaded.net/file/7skdtm80
410 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Looking for direct download link...
411 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Direct download link not found
412 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Checking for link errors...
413 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: No errors found
414 09.01.2016 22:04:43 INFO    HOSTER UploadedTo[6]: Processing as free download...
415 09.01.2016 22:04:43 INFO    CAPTCHA UploadedTo[6]: ReCaptcha | Using OCR to decrypt captcha...
416 09.01.2016 22:04:43 WARNING CAPTCHA UploadedTo[6]: ReCaptcha | No OCR result

Please note that when I enter my account info, it is first considered as non premium
485 09.01.2016 22:13:39 INFO    ACCOUNT RealdebridCom: Adding user `bl0wwaffee`...
486 09.01.2016 22:13:39 INFO    ACCOUNT RealdebridCom: Login user `bl0wwaffee`...
487 09.01.2016 22:13:40 INFO    ACCOUNT RealdebridCom: Updating account info for user `bl0wwaffee`...
488 09.01.2016 22:13:40 INFO    ACCOUNT RealdebridCom: Relogin user `bl0wwaffee`...

But once I restart pyload, it is considered premium :
540 09.01.2016 22:15:36 INFO    ACCOUNT RealdebridCom: Adding user `bl0wwaffee`...
541 09.01.2016 22:15:36 INFO    ACCOUNT RealdebridCom: Login user `bl0wwaffee`...
542 09.01.2016 22:15:37 INFO    ACCOUNT RealdebridCom: Grabbing account info for user `bl0wwaffee`...

Do you think it might be related ?

Thanks

**Comment by Maltro** [comment]
Hello,
I've got the same issue I think, altough I'm using rehost.to instead of Realdebrid.

Rehost Account is configured as premium (there isn't any setting to activate rehost plugin):
10.01.2016 21:08:23 INFO      ACCOUNT RehostTo: Adding user `0000`...
10.01.2016 21:08:23 DEBUG     ACCOUNT RehostTo: Reached login timeout for user `0000`
10.01.2016 21:08:23 INFO      ACCOUNT RehostTo: Login user `0000`...
10.01.2016 21:08:23 DEBUG     ACCOUNT RehostTo: LOAD URL https://rehost.to/api.php | redirect=True | cookies=True | get={'cmd': 'login', 'user': '0000', 'pass': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.01.2016 21:08:23 INFO      ACCOUNT RehostTo: Grabbing account info for user `0000`...
10.01.2016 21:08:23 DEBUG     ACCOUNT RehostTo: LOAD URL https://rehost.to/api.php | redirect=True | cookies=True | get={'cmd': 'login', 'user': '0000', 'pass': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.01.2016 21:08:23 DEBUG     ACCOUNT RehostTo: LOAD URL http://rehost.to/api.php | redirect=True | cookies=True | get={'cmd': 'get_premium_credits', 'long_ses': u'*********************************'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.01.2016 21:08:24 DEBUG     ACCOUNT RehostTo: Size: 123456 | Unit: MB
10.01.2016 21:08:24 DEBUG     ACCOUNT RehostTo: Account info for user `0000`: {'login': {'timestamp': 12345678.123456, 'password': '**********', 'valid': True}, 'data': {'session': u'*********************************', 'premium': True, 'plugin': <Account RehostTo>, 'trafficleft': 123450000, 'maxtraffic': None, 'validuntil': 1234567890.0, 'login': '0000', 'type': 'RehostTo', 'options': {'limitdl': ['0']}}}

But Pyload won't use the rehost account for uploaded.to:
10.01.2016 21:12:20 INFO      Added package test containing 1 links
10.01.2016 21:12:20 INFO      Download starts: http://uploaded.net/file/8vpzhioe
10.01.2016 21:12:20 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
10.01.2016 21:12:21 DEBUG     HOSTER UploadedTo[1]: Plugin version: 1.01
10.01.2016 21:12:21 DEBUG     HOSTER UploadedTo[1]: Plugin status: testing
10.01.2016 21:12:21 WARNING   HOSTER UploadedTo[1]: Plugin may be unstable
10.01.2016 21:12:21 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
10.01.2016 21:12:21 INFO      HOSTER UploadedTo[1]: Grabbing link info...
10.01.2016 21:12:22 DEBUG     HOSTER UploadedTo[1]: Link info: {'status': 2, 'hash': {}, 'name': '200MB.zip', 'url': u'http://uploaded.net/file/8vpzhioe', 'pattern': {'ID': u'8vpzhioe'}, 'size': 209715200}
10.01.2016 21:12:22 DEBUG     HOSTER UploadedTo[1]: Previous link info: {}
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Link name: 200MB.zip
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Link size: 200.00 MiB (209715200 bytes)
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Link status: online
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Processing url: http://uploaded.net/file/8vpzhioe
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Looking for direct download link...
10.01.2016 21:12:22 DEBUG     HOSTER UploadedTo[1]: LOAD URL http://uploaded.net/file/8vpzhioe | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Direct download link not found
10.01.2016 21:12:22 DEBUG     HOSTER UploadedTo[1]: LOAD URL http://uploaded.net/file/8vpzhioe | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Checking for link errors...
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: No errors found
10.01.2016 21:12:22 INFO      HOSTER UploadedTo[1]: Processing as free download...

I also tried a fresh installation including deletion of the config folder, and let the UpdateManager update everything, but nothing changed.
After entering my account data, it was considered non premium, too, and a restart of pyload fixed it.
So I guess it's the same issue. Hope it gets fixed soon :)

Thanks.

**Comment by Piero87** [comment]
hi, i have the same problem, anyone have resolved the problem?

**Comment by Piero87** [comment]
I have the same problem

**Comment by Piero87** [comment]
@vuolter sorry if i bother you, but the Realdebrid plugin still doesn't work, there are any eta? Thanks for your work

**Comment by gregus69** [comment]
I think it's dead forever now :(

no update for this plugin T_T

**Comment by GammaC0de** [comment]
@gregus69 No it is not, @vuolter is currently in the middle of rewriting `MultiAccount` plugin.

**Comment by gregus69** [comment]
Hi,

TY for your reply

king regards

**Comment by GammaC0de** [comment]
:+1:

**Comment by shyriu42** [comment]
With megadebrid same thing   isn t used the debrid link   Direct download link not found

**Comment by salimimani** [comment]
Thank you @GammaC0de for the update !

In the meantime, there is this workaround, if you're using realdebrid (probably the same with other multihosters) :

- Open realdebrid on browser
- Paste links in "unrestrain" input box on realdebrid.com
- Check box "show generated links"
- Click unrestrain
- Copy/Paste generated links into pyload
==> links will be considered as realdebrid links as if realdebrid were a standard hoster

It's a little bit longer to do than just past uploadedTo (or other) links to pyload and have them downloaded automatically with realdebrid, but at least it works :)

**Comment by gregus69** [comment]
Hello,
can you give me news for the update

ty

**Comment by vuolter** [comment]
See: https://github.com/pyload/pyload/issues/2121

**Comment by Piero87** [comment]
I use the workaround, for the Realdebrid problem, so paste the link on realdebrid generate the link and paste it on pyload to use the BasePlugin, but in the last two days the plugin the 90% of time doesn't work, and give me this error:

Parse error: No file downloaded | Plugin may be out of date 0.00 B

any idea? :(

**Comment by sveni-lee** [comment]
Hello!

 

New message, please read <http://ms-studio.co/mere.php?jx>

 

sveni_lee@gmx.de

**Comment by sveni-lee** [comment]
Hey,

Have you heard about that really wowsome stuff? You won't regret, believe me, read more here <http://gijaslesti.gjura.com/aejwlhp>

Good wishes, sveni_lee@gmx.de
