### ISSUE TITLE
UNC download path not working

### ISSUE THREAD

**Issue by codenamedelta** [pyload/pyload#2284]
I have had the download path set in settings set to a UNC path since I first started using this, however a few days ago this stopped working.

Example path: \\fileserver\video\downloads

Instead of pyload saving to the above path, it downloads to my local system under the following path:

C:\fileserver\video\downloads

No error regarding the file path appears in the debug log and the downloads still work, but they are no longer going to the correct location.

**Comment by youlJunior** [comment]
@codenamedelta do you have last update of Pyload ?

**Comment by codenamedelta** [comment]
I just downloaded the latest. Still same issue, but just saw your additional remark...I have tried using a mapped drive, but it gives me a space issue. I am guessing that this may be due to the fact that I have pyload setup to run as a task, so the account may be running elevated and have no access to the mapped drive.

**Comment by youlJunior** [comment]
@vuolter @GammaC0de 

The code in Hoster.py and misc.py make download folder work like that :
 - in Hoster.py the folder in config is transformed to absolute path, so :
    - an absolute path is ok
    - a relative path is ok
    - a UNC path is handled like an absolute path because python doesn't handle correctly UNC : 
```
Note : On Windows, many of these functions do not properly support UNC pathnames. splitunc() and ismount() do handle them correctly. 
``` 
- in misc.py (safepath sunction) :
    - the safepath function take a path as it is absolute, so any relative path is considered as absolute

I think both of these python files must be modified in order to make UNC path work again.

**Comment by youlJunior** [comment]
@codenamedelta :

Could you try that :

In internal/Hoster.py :
- line 282, replace
```python
dl_folder = os.path.abspath(self.pyload.config.get('general', 'download_folder'))
```
by
```python
dl_folder = self.pyload.config.get('general', 'download_folder')
```

In internal/misc.py
- replace "safepath" function (line 475 to 499) by :
```python
def safepath(value):
    """
    Remove invalid characters and truncate the path if needed
    """
    #value = os.path.abspath(value)
    if os.name == "nt":
        unt, value = os.path.splitunc(value)
    else:
        unt = ""
    drive, filename = os.path.splitdrive(value)
    #filename = os.path.join(os.sep, *map(safename, filename.split(os.sep)))
    filename = os.path.join(os.sep if os.path.isabs(filename) else "", *map(safename, filename.split(os.sep)))
    path = unt + drive + filename

    try:
        if os.name != "nt":
            return

        length = len(path) - 259
        if length < 1:
            return
        
        dirname, basename = os.path.split(filename)
        name, ext = os.path.splitext(basename)
        path = unt + drive + dirname + truncate(name, length) + ext

    finally:
        return path
```

**Comment by codenamedelta** [comment]
I tested and that worked perfect. Thank you @youlJunior

**Comment by GammaC0de** [comment]
@youlJunior this change was made because of #2275
Have you tested it with relative download path?

**Comment by youlJunior** [comment]
@GammaC0de 

The root cause of #2275 was because the "safepath" function was handling any path in parameter as absolute.
Si when you had a relative path in config, the function added a separator in front to make it absolute.
Ex : "Downloads" in config became "/Downloads"

You made two fixes in Hoster.py and in function "safepath", by using os.path.abspath(path) in order to transform path to a real absolute path before using "safepath".
It worked, but abspath() can't deal with UNC path.

My modifications make safepath work good (relative path stay relative, absolute stay absolute, UNC stay UNC...)
So now you don't need to convert path from relative to absolute before working with it.

Anyway I'm going to test Pyload in Linux and Windows with relative, absolute and UNC dirs.
I'll post results in the evening.

**Comment by GammaC0de** [comment]
:+1:
