### ISSUE TITLE
versioning, stable branch isn't stable

### ISSUE THREAD

**Issue by randoom42** [pyload/pyload#2292]
First of all: I'm grateful for every active FLOSS dev. And I really appreciate(d) pyload.

But during the last year or so my previously really good pyload experience has been seriously worsened:
- Too often automatic updates just break stuff.
- The deb package is seriously out of date (although it carries the same version number).
- Even structural things seem to change in the (so called) stable branch.

I just migrated to raspbian jessie on a new RPi 2. The first days there were serious issues in the pyload base that broke downloads. Now I still can't seem  to get two plugins working that are essential to me and that worked before:
- Captcha_9kw (original from 9kw.eu, the two (!) included ones are even more outdated)
- DirectDownloadFetcher for the personal RSS feed of directdownload.tv (from the forums before that stopped working, too)

It seems that the whole hook mechanism changed to some addon stuff, periodical() became periodical_task() and so on.

**Why in hell would you do such things in "stable"?** Please get a dev or nightly branch and play there. Only fix bugs in stable and release new stuff in new versions. Right now you are scaring people away. It's a pity because I once thought it was a really good project that just worked. And right now, with the pyload.org down as well, it feels like it's going down the drain.

**Comment by c0rrre** [comment]
this would be a greate idea

**Comment by nordic-style** [comment]
This is issue number 120845234  that is asking this question. And yes - it is still open.

**Comment by Brueggus** [comment]
+1

Multihoster stuff is another example which is broken for months.

**Comment by vuolter** [comment]
Recently I created indeed a new branch called "testing"... :p
My monthly schedule is more than "full". For example in my mind now there are:
* Fix MultiHoster framework (working on)
* Fix Checksum plugin (done, not merged yet)
* Fix recent encoding issues (I really don't know how...)
* Write YetiShare plugins (done, not merged yet)
* Write a Duplicate download checker plugin (done, not merged yet)
* Fix SkipRev (working on)
* Fix ExtractArchive (maybe 30% done; I said 50% before but I was totally wrong)
* Rewrite UpdateManger to sync with the github repo directly (done, testing phase)
* Finish the js implementation for pyload.github.io
* Start the wiki
* **Resume work on 0.4.10**

**Comment by randoom42** [comment]
@vuolter: Of course it's a good thing you're motivated. But I'm afraid you missed the point here: Your "stable" isn't stable, self destructs regularly, undergoes infrastructure changes that render plugins useless without any version change (BTW: Is there any documentation about the change and the situation now?). You seriously upset users that way. And you can read that on other boards as well when the pyload topic comes up.

**This is not a question. It is a report of a most essential bug.** The project is missing some thoughts about releases, development organisation and a real stable branch instead of messing in stable constantly. Most people don't want a nightly that dismantles every other day. Continue like that and you might be riding a dead horse in a not so distant future.

Please, take a step back an ask you self:
a) if you wanted/enjoyed to use a software like that,
b) if you are doing this just for yourself or if you enjoy creating something great  and useful that others use, too.
c) what has to change here.

**Comment by Velociraptor85** [comment]
yap I found that also very disappointing that it went from -working dont care-  to -wtf is happening now again- 

but it seems like there is a major rewrite of the code going on, sadly this is happening in stable branch which is not that smart as @randoom42 said

BUT I appreciate all the work @vuolter and @GammaC0de is doing _really_, but maybe this could be done in dev branch with some merging to stable

**Comment by nordic-style** [comment]
Imho the actual the work should be done in master?!

**Comment by 1337sup3rh4x0r** [comment]
I understand your point, but still, this is github guys. A development community. Why don't you fork this from a point where it worked for your usecase? 
With multiple filehosters changing stuff all the time, I guess we will never see a fully working, 100% stable, fool-proof release. It's simply a sysiphus struggle.
I find it understandable that it is more fun for a dev who uses his free time on such a project to do a fundamental code rewrite than doing proper project management. And on github everybody should be able to at least roll back to a working version and disable update manager.
I think we shouldn't forget that they owe us nothing and I still find it amazing how they squish bugs in here everyday. Yeah, maybe its a bit unorganized, but then instead of complaining why not offer help?

**Comment by Velociraptor85** [comment]
I think we shouldn't forget that they owe us nothing and I still find it amazing how they squish bugs in here everyday. Yeah, maybe its a bit unorganized, but then instead of complaining why not offer help?
------------------------
How can I help =)?

**Comment by vuolter** [comment]
As I promised before, from 0.4.10 release on, the stable branch will be stable.

**Comment by randoom42** [comment]
@vuolter: Thank you very much. I didn't see any statement like that before.

@1337sup3rh4x0r: @Velociraptor85 put it in a nutshell, pyload went from "working don't care" to "wtf is happening now again" every other day. And that is totally unnecessary following some basic development practices and using git. It wouldn't be a big deal porting hoster fixes to stable either.
Of course "they" don't owe us anything. But, speaking from my perspective, when I create something I also take pleasure in doing it right. And having a "stable" that is actually a nightly during a big rewrite... that is just bad practice.
Also I don't at all share your point that everyone could just fork, disable updates and return it to a working state. That is just an unnecessary waste of time. Do you want me to do that on every FLOSS project I use? Your joking, right? IMHO it's more "fun" and rewarding to do it right in the first place.

Anyway, once pyload is back to old stability I'd see myself donating as a form of contribution.

**Comment by 1337sup3rh4x0r** [comment]
Yeah, your perspective. You would do it right. But from my perspective it's bad practice to give smart advice to "step back and ask yourself what has to change". It's your opinion that something has to change.

**Comment by nordic-style** [comment]
~~Well - the main problem is that a branch that is called "stable" does not make much sense if it is not the stable branch. I also know that @vuolter has a different opinion ~~

###People that are new to pyload will think:

Ah too bad that the website is down - but wait - there is a "official" github repo with a stable branch - just let me clone that one. No one will check if anyone has forked a "real-stable" pyload version.

Since it is still a lot of work to create a more or less stable branch of pyload we need more people who can support @vuolter and @GammaC0de . Maybe lets not call it stable but "working" branch - or whatever.

I will try to fix some bugs myself in the near future and after that i might have enough understanding to help out creating such a branch.

**Comment by segelkma** [comment]
@1337sup3rh4x0r you seem to forget that not everyone is capable of doing so. Pyload is not supposed to be a download manager just for people with skills in coding and github in general, at least it wasn't in the past. If that changed, then I can tell by sure that the amount of user will decrease rapidly. Luckily, vuolter already stated that this is not the case. A few days ago I moved to JDownloader  2 (officially still beta, but its just working great), even though it uses alot more ram on my very limited ds215j and the shitty webinterface, but I can't help it. Recently pyload was just too much of semi working download manager where I had to fix alot to make it work the way I want, until I update again. I will try again 0.4.10 and hope it is indeed stable then.

**Comment by randoom42** [comment]
@1337sup3rh4x0r I'm sorry, I can't take you seriously. You seem very ignorant to me. The software dismantles every other day, has a "stable" that clearly isn't even intended to be stable. And you say that is alright and not a bug. Although there are techniques to improve this that - using git the way it's intended and a moment of thought - aren't that much of an effort to implement and would mean a HUGE benefit to everyone, including the devs.

FLOSS projects like this very often are a learning exercise for the author as well. We clearly don't have an experienced dev here. You will take it as arrogant, for me it would be common consensus when I say that the author would benefit personally from doing it right and learn something on the way. Continuing the current approach on the other hand will cost the project more of its already diminished reputation and lead to insignificance. And if all this was just a personal fun thing, why would the dev fix bugs for or implement hosters he doesn't use himself?

@nordic-style: It's not only people who think "let's use the git version, looks official and stable", it was stated in the forums by @vuolter to please use the git downloads as the website download section is outdated. In a pinned thread.

Anyway, I was just trying to help. I can move on to jdownloader as well as many others will. But I feel sorry as pyload suited my needs perfectly once.

**Comment by godfuture** [comment]
@1337sup3rh4x0r if you are right, pyload will die (. Pyload is still great, as many know how powerful and feature rich it is. But in case only devs know to use it, it will be just another close to death repo.

@vuolter @GammaC0de 
Shouldnt there be some "core components" that get branched for significant changes? The plugins then should reference the branch (core) they depend on. So that the udpate manager does not fetch plugin changes that are incompatible with core. The issue, as I understood, is as well that this "core" itself is a module and gets update regularily. And I guess it is not easy to destinguish what would belong into such a core and what not...but branching these core functionalities would be a step forward.

**Comment by GammaC0de** [comment]
`stable` is stable again.
