### ISSUE TITLE
Getting html response when BadHeader is encountered

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#2565]
It appears that Rapidgator enjoys playing with return codes:

```
% curl -D head 'http://rapidgator.net/api/file/download?sid=[...]&url=http://rapidgator.net/file/[...]'
{"response":null,"response_status":505,"response_details":"Delay between downloads must be not less than 0 min. Don`t want to wait? Upgrade to Premium and forget about delays!"}
% head -1 head 
HTTP/1.1 505
```

Likewise, it will throw a 503 error with "response_details" matching `DOWNLOAD_LIMIT_ERROR_PATTERN` if we're out of downloads for the hour. The way pyload currently handles such "BadHeaders" is to throw an exception in the process of which the content of the actual webpage is unrecoverably lost. However, this content contains crucial information. I don't see a way of fixing this without touching `HTTPRequest.py` which should not be done in the stable branch, am I right? What are the options to get the content of the HTTP response even though the header contains a "bad" code?

**Comment by GammaC0de** [comment]
The design of `BadHeader` exception was meant to contain a `e.content` attribute but because of a bug `e.content` does not get filled.

I actually already spotted this bug in the past and issued a PR for v0.5 (https://github.com/vuolter/pyload/pull/17) so it should be fixed in the upcomming version (@vuolter when !?????)

Fixed version: https://github.com/GammaC0de/pyload/blob/1f8acaefb33faacbe85fc00ae961f1ab7ae6e8e8/pyload/network/HTTPRequest.py

**Comment by igel-kun** [comment]
Ah that's awesome, thanks (had to modify imports slightly to incorporate into 0.4.9). It seems to work well so far, but in regular 0.4.9 it seems Rapidgator keeps broken :/

**Comment by GammaC0de** [comment]
Yes, So is `CloudSix` https://github.com/pyload/pyload/issues/2305 and probably others :disappointed:

**Comment by GammaC0de** [comment]
Already merged to `stable` so closing.
