### ISSUE TITLE
SimpleCrypter handle_pages problem

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#2603]
I think there might be a _serious_ problem in ```SimpleCrypter.py``` when handling pages:
The idea, if links are spread over pages, seems to be: For each page,
1. call ```load_page()``` to get the HTML into ```self.data``` ([line 271](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/SimpleCrypter.py#L271))
2. call ```get_links()``` to parse links
3. merge links into ```self.links```.
However, the current implementation of ```get_links()``` _erases_ ```self.links``` (in [line 254](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/SimpleCrypter.py#L254)) which holds all previously parsed links.

**Comment by GammaC0de** [comment]
Are you sure?
Tthis code was a fix to https://github.com/pyload/pyload/issues/2499

**Comment by igel-kun** [comment]
Well, I did observe this problem on my fork, which slightly differs from the stable branch, so I cannot be 100% certain. However, my argument here is only on the code that I linked. I don't see how any link on page 1 can survive line 254.

**Comment by GammaC0de** [comment]
`get_links()` should return a list of links, not fill `self.links[]`
It does this by calling `handle_free()` or `handle_premium()` (which do fill `self.links[]`) and then `handle_pages()` appends the returned list to `self.links[]`
So you see the problem here: `handle_pages()` appends  `self.links[]` but `handle_free()` or `handle_premium()` sets it.

**Comment by igel-kun** [comment]
Ah thanks for the explanation and the patch - I actually did almost the same thing to my fork to fix it :)
