### ISSUE TITLE
Plugin Uplea ==> Pyload

### ISSUE THREAD

**Issue by RickyLoad** [pyload/pyload#2632]
Hello,

After an update yesterday, I have no access to my premium account Uplea.
Previously I used LetitbitNet.
What is the new plugin for Uplea?
Thank you and see you soon

**Comment by GammaC0de** [comment]
> Previously I used LetitbitNet.

Why did you stopped using LetitbitNet?

As for Uplea, I will need account info and a sample URL for testing.
Please send your account info to nitzo2001 at yahoo dot com.

**Comment by RickyLoad** [comment]
I have not stopped LetitbitNet, it is not in the activated plugins.
I have a seedbox ==> useed
and unfortunately I can Interacting with my premium account Uplea.
Do you have another plugin activated for Uplea !!
Thank you and see you soon

**Comment by GammaC0de** [comment]
letitbit.net site is down,  isn't it? if I go to letitbit.net, I get this message: "The project does not exist"

As for Uplease, as I told you above, I need you to email me your user and password for Uplea so I can test the plugin.
Send it and a sample URL to  nitzo2001 at yahoo dot com.

**Comment by RickyLoad** [comment]
I send you an email

**Comment by RickyLoad** [comment]
what new ?? You see what plugin replaces LetitbitNet in pyLoad ??

**Comment by GammaC0de** [comment]
Still working on Uplea,  will let you know when Finished . Can you tell me what is the problem with LetitbitNet ?  Is the web site working for you ? 

 

 RickyLoad<notifications@github.com> wrote:   
what new ?? You see what plugin replaces LetitbitNet in pyLoad ??

**Comment by GammaC0de** [comment]
Update your plugins, it should work now.

**Comment by GammaC0de** [comment]
>Hello,
I raised my pyLoad for updater my plugins as you have advised me. results:
It seems he can not find the plugin Letitbit.net !!! I do not understand anything anymore.
>
What should I do ??

@RickyLoad You asked for a to use your Uplea account with pyLoad, now you can.

I keep asking you, does the website letitbit.net works for you, you don't answer me.
because for me it does not work - I get `"The project does not exist"` message.

So, does letitbit.net works for you??
Please provide sample URL.
