### ISSUE TITLE
Your project sucks, seriously.

### ISSUE THREAD

**Issue by angryuser** [pyload/pyload#2636]

**Comment by DIG-** [comment]
JDownloader is good since I've started downloading in 2012, but 'cus is a java application, when i open a game, all downloads slow down the speed. Then i switched to other program with same capabilities.
Recently i installed a small linux server in home and try JDownloader with web interface, but it is ugly and needs third-party authentication. Just trash. And thats why i'm here with pyload. Now i'm creating a new web interface for pyload (at first only for me).

**Comment by vuolter** [comment]
@angryuser If you do not attach a debug log, we can not ever be able to investigate about the issues you report.
Plus:
- You may want to check the backup of the old forum: https://twitter.com/pyload/status/706646435538866176.
- Not true: there're issues, but not critical as you say. But if you spot something, please open a ticket and post the log.
- Same as above, debug log please.
- Yep, the core is old (I'm working on it, but is not easy and I'm not paid...). but plugins are periodically updated by our dev @GammaC0de and other collaborators here. **I am forever grateful to them all!**
- Never reported. I think you know what to do if you really want to help...
**Summing, if your intention is to simply yell at us, please stop with this childish attitude and go away.**
Regards.
