### ISSUE TITLE
pyLoad on RPi2 - How do I roll updates and why does ul.net not work?

### ISSUE THREAD

**Issue by Vesanius** [pyload/pyload#2640]
Hey there

I'm pretty new on github, no special console skills - average computer user. I want my RPi2 to download things for me on my external HDD, but I struggle with configuring pyLoad correctly. First of all, the ul.net Plugin seems outdated. Also, the litte bar on the right top of the web-interface said me, that there would be an update. Because restarting pyLoad didn't update anything, I decided to do some research and I found an alternative UpdateManager.py, with which I replaced the old one. The message on the little bar disappeared, but in the log is anyway written, that there would be an update.

Log:

> 392	05.11.2016 00:04:13	INFO	*** New pyLoad Version
> 396	? 	?	
> 397	? 	?	
> 398	? 	?	
> 429	? 	?	
> 430	? 	?	
> 431	? 	?	available ***
> 438	05.11.2016 00:04:13	INFO	*** Get it here: http://pyload.org/download ***
> 439	05.11.2016 00:04:13	INFO	No plugin updates available
> 440	05.11.2016 00:31:53	INFO	shutting down...
> 441	05.11.2016 00:31:53	INFO	Received Quit signal
> 442	05.11.2016 00:32:04	INFO	starte pyLoad 0.4.9
> 443	05.11.2016 00:32:04	INFO	Benutze Home-Verzeichnis: /root/.pyload
> 444	05.11.2016 00:32:05	INFO	ExtractArchive: Aktiviert UnRar UnZip
> 445	05.11.2016 00:32:05	ERROR	Fehler beim importieren von UpdateManager: No module named Addon
> 446	05.11.2016 00:32:05	INFO	Aktivierte Plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
> 447	05.11.2016 00:32:05	INFO	Deaktivierte Plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
> 448	05.11.2016 00:32:05	INFO	Downloadzeit: True
> 449	05.11.2016 00:32:06	INFO	Starting builtin webserver: 0.0.0.0:8000
> 450	05.11.2016 00:32:06	INFO	Free space: 25.61 GiB
> 451	05.11.2016 00:32:06	INFO	Activating Accounts...
> 452	05.11.2016 00:32:06	WARNING	UploadedTo: Could not login with account XXXXXX | (6, 'Could not resolve host: uploaded.to')
> 453	05.11.2016 00:32:06	INFO	Activating Plugins...
> 454	05.11.2016 00:32:06	INFO	pyLoad is up and running 

How can I get the update installed and my ul.net account to work?

Sincerely, and thanks in advance!
Vesanius

**Comment by GammaC0de** [comment]
Please read #2000

 

   
Hey there

I'm pretty new on github, no special console skills - average computer user. I want my RPi2 to download things for me on my external HDD, but I struggle with configuring pyLoad correctly. First of all, the ul.net Plugin seems outdated. Also, the litte bar on the right top of the web-interface said me, that there would be an update. Because restarting pyLoad didn't update anything, I decided to do some research and I found an alternative UpdateManager.py, with which I replaced the old one. The message on the little bar disappeared, but in the log is anyway written, that there would be an update.

Log:


392 05.11.2016 00:04:13 INFO *** New pyLoad Version
396 ? ?
397 ? ?
398 ? ?
429 ? ?
430 ? ?
431 ? ? available ***
438 05.11.2016 00:04:13 INFO *** Get it here: http://pyload.org/download ***
439 05.11.2016 00:04:13 INFO No plugin updates available
440 05.11.2016 00:31:53 INFO shutting down...
441 05.11.2016 00:31:53 INFO Received Quit signal
442 05.11.2016 00:32:04 INFO starte pyLoad 0.4.9
443 05.11.2016 00:32:04 INFO Benutze Home-Verzeichnis: /root/.pyload
444 05.11.2016 00:32:05 INFO ExtractArchive: Aktiviert UnRar UnZip
445 05.11.2016 00:32:05 ERROR Fehler beim importieren von UpdateManager: No module named Addon
446 05.11.2016 00:32:05 INFO Aktivierte Plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive
447 05.11.2016 00:32:05 INFO Deaktivierte Plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
448 05.11.2016 00:32:05 INFO Downloadzeit: True
449 05.11.2016 00:32:06 INFO Starting builtin webserver: 0.0.0.0:8000
450 05.11.2016 00:32:06 INFO Free space: 25.61 GiB
451 05.11.2016 00:32:06 INFO Activating Accounts...
452 05.11.2016 00:32:06 WARNING UploadedTo: Could not login with account XXXXXX | (6, 'Could not resolve host: uploaded.to')
453 05.11.2016 00:32:06 INFO Activating Plugins...
454 05.11.2016 00:32:06 INFO pyLoad is up and running


How can I get the update installed and my ul.net account to work?

Sincerely, and thanks in advance!
Vesanius

**Comment by Vesanius** [comment]
> Please read [#2000](https://github.com/pyload/pyload/issues/2000) 

Thanks a lot. I've now deleted the old one by using "sudo rm UpdateManager.py" and sudo w"got" the new one. I started my Pi new, and then the log said, there would be new Plugin Updates. So I decided to restart pyLoad, but unfortunately, I can't reach it anymore by using the web-interface on my computer. webmin says, that there is no process called pyLoad running. How can I fix this?

Sincerely,
Vesanius

P.S: Even rebooting my Pi won't work...

**Comment by Vesanius** [comment]
Little update: I've now removed my pyLoad-directory (/home/bin/.pyload) and want to reinstall pyLoad. Now the log in Putty says as following:

> root@raspberrypi:/home/pi# cd /usr/share/pyload
root@raspberrypi:/usr/share/pyload# ./pyLoadCore.py
05.11.2016 12:36:04 INFO      starte pyLoad 0.4.9
05.11.2016 12:36:04 INFO      Benutze Home-Verzeichnis: /root/.pyload
05.11.2016 12:36:05 INFO      ExtractArchive: Aktiviert UnRar UnZip
05.11.2016 12:36:05 INFO      Aktivierte Plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
05.11.2016 12:36:05 INFO      Deaktivierte Plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
05.11.2016 12:36:05 INFO      Downloadzeit: True
05.11.2016 12:36:06 INFO      Starting builtin webserver: 0.0.0.0:8000
05.11.2016 12:36:06 INFO      Free space: 25.50 GiB
05.11.2016 12:36:06 INFO      Activating Accounts...
05.11.2016 12:36:06 ERROR     Error importing UploadedTo: No module named Account
Traceback (most recent call last):
  File "./pyLoadCore.py", line 667, in <module>
    main()
  File "./pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by GammaC0de** [comment]
@Vesanius Use `./pyLoadCore.py -d` to view debug information.

**Comment by Vesanius** [comment]
Love you, @GammaC0de ! Got it working by mlocating all pyload directories, deleting the hell out of them and reinstalling as your linked tutorial says. Works like a charm.

Supernatural powers of all religions may bless you.
