### ISSUE TITLE
CLick n Load dont work

### ISSUE THREAD

**Issue by pascalschmiederer** [pyload/pyload#2665]
The last few days Click n Load doesen't work on a few tested pages.

Just throws an error in the WebIF or it happen nothing. 

`An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/home/server/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/home/server/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/home/server/pyload/module/web/cnl_app.py", line 22, in _view
return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)`

**Comment by GammaC0de** [comment]
Duplicate, see #1784

**Comment by pascalschmiederer** [comment]
There are two Problems. The 500 is maybe a duplicate but the other is new and does not throw the 500 error.

**Comment by GammaC0de** [comment]
, pe@pascalschmiederer If you have more problems, please specify them.

**Comment by pascalschmiederer** [comment]
Did not saw the changes in 1784 sorry.  NOW it work again. Thx.

**Comment by GammaC0de** [comment]
👍

**Comment by pascalschmiederer** [comment]
Why you dont change it in the main code?

**Comment by GammaC0de** [comment]
Because the policy is not to change anything beside plugins in the `stable` branch.
Changes like that has to wait to the next pyLoad release (which actually had not happend in few years 😢 )

I did not set this policy, I  inherited it.

Hopefully this will change in the near future, @vuolter should release a new version soon.
