### ISSUE TITLE
Fix #2000 in readme?

### ISSUE THREAD

**Issue by Slevin7** [pyload/pyload#2707]
@GammaC0de 
is it possible to put the fix  #2000 in the readme?
i mean whenever i look in the Issues to search if there is anything new about 0.5 2 or 3 issues is about the same.

maybe it would be better if the solution is postet in the readme.

Just thinking

**Comment by GammaC0de** [comment]
We are all waiting for @vuolter to finish v0.5, then #2000 will not be relevant anymore because you would install pyLoad via `pip` and that way pip will also install all the needed dependencies for you.

I  think that the wiki is the suitable place for #2000 and the readme should add a reference to the wiki.

Anyway, I give @vuolter the responsibility for such things, my focus is on plugin fixup/development and issues support.
