### ISSUE TITLE
Python 2.5 support.

### ISSUE THREAD

**Issue by VinceGitHub** [pyload/pyload#2772]
Hi,
from the README: "...You need at least python 2.5 to run pyLoad...". I think this is outdated since you decided to drop python 2.5 support. Can someone correct these requirements to the actual ones in the readme?

**Comment by GammaC0de** [comment]
Python 2.5 support is resumed, update your plugins. 

 

 VinceGitHub<notifications@github.com> wrote:   
Hi,
from the README: "...You need at least python 2.5 to run pyLoad...". I think this is outdated since you decided to drop python 2.5 support. Can someone correct these requirements to the actual ones in the readme?
