### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by kiamgrebgnur** [pyload/pyload#2806]
Hi,

I'm using pyload for many years and it's such a great tool but now I want to update (reinstall) it and couldn't.
None of the suggestions works. There is no pyload-ng in pip, I've tried to do `python setup.py install` which seems to work but if I try to start pyload I get 

> ImportError: No module named pyLoad

I want to use the latest version (master branch) not the 6 years old 0.4.9 release.

So how can I install it?  
My os is Ubuntu 16.04.2 LTS.

Thanks in advance.

**Comment by Slevin7** [comment]
the master branch is not ready yet, so you still have to use the stable

**Comment by Bruzzlee** [comment]
Could you please add a note to the documentation that it is not ready yet?
At first I lost a lot of time because I've used python 2.7 which does not work with the new setup.
Then I figured it out that I need to use sudo -H pip3 .... to install the missing packages.
Then there was a problem with the enum package. I had to install enum34

Now I ended up with the same error like kiamgrebgnur.

A little side note would have saved me a lot of time... (as I am not familiar with pip)
BTW: Great work so far!

Thank you
Bruzzlee

**Comment by GammaC0de** [comment]
@Bruzzlee See #2000

**Comment by Bruzzlee** [comment]
@GammaC0de I already have a working "0.4.9" version running. I wanted to upgrade to the new v5 but It seems I am to early.

**Comment by GammaC0de** [comment]
Yes, v0.5 is cosidered pre-alpha.

**Comment by vuolter** [comment]
I get it. Time to put a big warning in the first page.
