### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Mattpenfold** [pyload/pyload#2814]
I have a number of backend servers running, and use nginx as a reverse proxy to access them. 

That all works fine, but I also want to use nginx to do the authentication. Is there anyway of configuring pyLoad so as not to ask for a login name and password?

**Comment by GammaC0de** [comment]
@Mattpenfold I don't know if it helps you but there is a PR to make pyLoad authenticate against LDAP server (#1966)

**Comment by GammaC0de** [comment]
Also, although I did not tried if it actually works but you retrieve a session id if you do a POST to http://IP:Port/api/login with arguments 'username' and 'password' as a pyload user and password.
After that when you access pyload, you set a  'beaker.session.id' cookie with the session id retrieved before as value.

**Comment by Mattpenfold** [comment]
LDAP would be a possblty. Been a while since I set up an LDAP server though

Could I put in a feature request for a cons file flag that disables pyload authentication please? Because although LDAP would work, it seems a bit of overkill to run another service when nginx I had an authentication module built in.

**Comment by GammaC0de** [comment]
And what about retrieving a session cookie?
you can retrieve a session cookie on server startup and then use if from now on..

**Comment by Mattpenfold** [comment]
To be honest that is stuff I don't know much about. 

Since I have reverse proxy working, I think I will leave it as it is and just let pyload do the authentication.

**Comment by kugan49** [comment]
Hi,

I'm instersted about your nginx config because location won't work with pyload.
Can you post it here ?

**Comment by GammaC0de** [comment]
@kugan49 Please open a new issue, I will try to help you.

**Comment by yannouchou** [comment]
Can we revive this feature request?
Like many (most?) users I'm running this behind a proxy that handles all the authentication/authorization logic once, so that it does not have to be managed separately in every individual back-end. So I just need to unplug authentication altogether.
The suggested workaround is not really elegant and cannot be easily implemented at the proxy level without some coding.

**Comment by NoxInmortus** [comment]
Hi, is this issue still worked on ? I'm on the same user case.

thanks

**Comment by bkanuka** [comment]
I would add that nginx can easily add a header to the proxied backend. So this bug (proxy authentication) could also be solved by having pyload read the HTTP Basic Auth header:

>  `Authorization: Basic <credentials>`, where credentials is the base64 encoding of id and password joined by a single colon.

Or, by having pyload "naively" authenticate against a header such as: `REMOTE_USER <username>`.

Option 1 (which is just Basic Auth) is probably preferable because it's a little bit safer - you need to know the password to authenticate.

**Comment by bkanuka** [comment]
It looks like this will be "fixed" in the 0.5 release because there will be an autologin option on the webui. If you want different users in pyload but still have nginx do the auth (maybe through vouch?) then header auth will also be straightforward to implement in 0.5.  I could do it, but I have no intention in doing this to the 0.4.x releases when 0.5 will be such a massive refactor.  We'll have to wait for 0.5.

**Comment by GammaC0de** [comment]
@bkanuka Sadly 0.5 is far away, I am currently checking basic auth implementation for v0.4.

**Comment by GammaC0de** [comment]
@bkanuka Please update your pyload installation using the instruction in #3283,
Go settings -> webinterface and turn on `Use basic auth`

**Comment by GammaC0de** [comment]
No response, closing.
