### ISSUE TITLE
share online error

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#2826]
I very offen get this error `19.04.2017 10:02:06 WARNING   ACCOUNT ShareonlineBiz: Error loading info for user `**********` | (35, 'gnutls_handshake() failed: An unexpected TLS packet was received.')`
and
`19.04.2017 10:02:05 WARNING   ACCOUNT ShareonlineBiz: Error loading info for user `**********` | (35, 'GnuTLS recv error (-54): Error in the pull function.')` . And the files are only 14 bytes.

**Comment by GammaC0de** [comment]
Which OS are you running?

**Comment by Mister-XY** [comment]
Ubuntu

**Comment by GammaC0de** [comment]
` sudo apt list --installed | grep libcurl`
Try updating this package.

**Comment by Mister-XY** [comment]
very strange, today the same error.
`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libcurl3-gnutls/zesty-updates,zesty-security,now 7.52.1-4ubuntu1.1 amd64  [Installiert,automatisch]
libgnutls-openssl27/zesty,now 3.5.6-4ubuntu4 amd64  [installiert]
libgnutls30/zesty,now 3.5.6-4ubuntu4 amd64  [installiert]
`

**Comment by Burnout5151** [comment]
Hi @Mister-XY, I guess your last quote is the output from the code @GammaC0de posted?
@GammaC0de wanted you to update these packages.
I personally think it is wise to update all packages.
This does that safely:
`sudo apt-get update
sudo apt-get upgrade`

This also updates the kernel ( a bit more risky but should be done from time to time as well, try it in the future)
`sudo apt-get update
sudo apt-get dist-upgrade`

Either way you will be asked if you want to continue. Then press 'y' or since you seem to have a german system 'j' should work as well.

**Comment by Velociraptor85** [comment]
@Mister-XY please let us know if you could resolve the issue

**Comment by Mister-XY** [comment]
@Velociraptor85 i have resolve this error. I don't use ist actualy. I have like this software for many years, but for some years, the software goes one stop forwards and two back

**Comment by Velociraptor85** [comment]
@Mister-XY sorry to loose you :) anyhow thanks for the info

**Comment by Mister-XY** [comment]
After many many time, i always use pyload to test. At first, i tested it on OMV 4 with Debian 9 stretch. And there is the same error.
Now i'm using Ubuntu 17.10 and i don't have this error. 
Actualy, it's all run fine.
