### ISSUE TITLE
How to manually trigger ExtractArchive

### ISSUE THREAD

**Issue by poste5** [pyload/pyload#2888]
I have the option ''Run after all downloads was processed: on'', but what does that mean? ExtractArchive will extract only when the entire package is complete? If I set the option to off ExtractArchive will ectract after each download of the package is complete?

ExtractArchive is working when the complete package is downloaded, the problem is that when I download a package of 10 files and for example 3 files fail because the files are offline, ExtractArchive does not extract the 7/10 files. Is that normal? Also, if I delete the failed downloads ExtractArchive does not start. It only start when a package is complete. Is there a way to trigger ExtractArchive to start extraction of that 7/10 files?

**Comment by GammaC0de** [comment]
"Run after all downloads was processed" means that (it least it should) ExtractArchive will extract only when all packages had completed.



>when I download a package of 10 files and for example 3 files fail because the files are offline, ExtractArchive does not extract the 7/10 files. Is that normal?

Is this a multivolume archive??

**Comment by GammaC0de** [comment]
No response, closing.

**Comment by poste5** [comment]
I have not explained myself very well due to english, sorry. It's not a multivolume archive. I mean, if I add 10 links to a package and for example 3 of this links are down (file erased from the hoster) ExtractArchive won't extract any file of the package. I will have a package with 7 completed downloads and 3 failed download.

**Comment by godfuture** [comment]
I am interested as well. Often some packages are not getting extracted. In these cases I have no chance but to re-download one file of the package and hope that this time it works. This was not a nice solution and therefore I used my own script, but now, due to whatever reason, it does not work anymore. 

Here is the script:
`/usr/bin/docker exec pyload find /downloads -type f -regex '.*\.part\(1\|01\)\.rar' -or \( -name '*.rar' -and ! -name '*part*' \) -exec sh -c '/usr/bin/unrar x -p- -o + "{}" "$(dirname "{}")" && rm -rf "$(dirname "{}")"/*.rar' \;`
