### ISSUE TITLE
ExtractArchive not delete folder

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload#2958]
Hello,
after a download has finished, extractarchive is extracting the archive as desired and deletes all parts of the archive. Is it possible to get the containing folder also being deleted?

Thanks

**Comment by GammaC0de** [comment]
So I guess you have configured pyLoad to put the extracted files outside the containing folder, right?

**Comment by UserX404** [comment]
Yes.
The extract-destinationpath differs from downloadpath

**Comment by GammaC0de** [comment]
What if the containing folder is not empty?

**Comment by UserX404** [comment]
Than it shouldn't be deleted. I'm asking if that's the desired behaviour? The delete jop could check if the folder is empty after deleting all archive files.

**Comment by GammaC0de** [comment]
Done, please test.

**Comment by UserX404** [comment]
Thx
First test looks good.

**Comment by hs1708** [comment]
This effectively breaks ExtractArchive, if you have packagenames that contain `http://` . This results in paths, that contain two slashes. I don't know why it was necessary to change pyPack.folder to pyPack.name, but the name has to be made pathsafe if it really is necessary. Furthermore the filebot hook has to be updated, since it expects the folder as an argument.

**Comment by GammaC0de** [comment]
pyPack.folder is empty if `Create folder for each package` in the general settings is is off (see`addPackage()` in `Api.py`).
Therefore if you set `ExtractArchive`'s `Extract files to folder:` to something other then the download folder and also set `ExtractArchive`'s `Create subfolder for each package` to true, no subfolder would have been created because pyPack.folder is empty.

I have updated the plugin to use `safename(pyPack.name)` only if pyPack.folder is empty.

**Comment by hs1708** [comment]
That should fix it, thank you!
