### ISSUE TITLE
Windows fresh install shows error with new UpdateManager.py

### ISSUE THREAD

**Issue by sebaro11** [pyload/pyload#3023]
On my clean pyload 0.4.9 installation on windows with the new UpdateManager.py the log gives me the following after the setup error:
(German Error Text)
`Fehler beim importieren von UpdateManager: No module named Addon`
It seems that other users on linux installations do not have this problem.

**Comment by GammaC0de** [comment]
How exactly did you installed pyload?

**Comment by sebaro11** [comment]
First I installed the python 3.6.3 for Windows software (python.org; pipe and IDLE).
After that I downloaded the Windows ZIP of 0.4.9 from here: https://github.com/pyload/pyload/releases
Next I exchanged the UpdateManager.py with the newest one.
And then I went through the setup and started pyload.

**Comment by iicaii** [comment]
In the current version of `UpdateManager.py` (https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/UpdateManager.py) the class `UpdateManager()` is an *AddOn* class. If you chose #2000 to install a brand new pyload, you downloaded the 0.4.9 release from 2013, which does not yet have the `AddOn.py` file (https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Addon.py), which the current `UpdateManager.py` needs. Hence it fails with the error message you pasted.

After facing a similar issue, I downloaded the stable branch of pyload (https://github.com/pyload/pyload/tree/stable, instead of the release) and extracted that one to `/usr/share/pyload/`. Currently, it looks like it works.

**Comment by sebaro11** [comment]
Hi iicaii,

thanks for the answer! That explains why the UpdateManager is not activated. But in the stable branch I do not find any executable windows version. 
I think I have to go with the command line one using: `python pyLoadCore.py`

**Comment by iicaii** [comment]
@sebaro11: Sorry! Should've said that I tested on Linux, where you run with the `python pyLoadCore.py` anyway.

**Comment by sebaro11** [comment]
@iicaii No Problem :) I copied everything out of the stable pyload and overwrited that on my windows 0.4.9 and now it works quite fine (UpdateManager has updated everything with the latest plugins) ^^
Thanks for your help :)

**Comment by GammaC0de** [comment]
@sebaro11 You have two options:
1. Use the stable branch using `python pyLoadCore.py` - includes some important bugfixes that the release doesn't.
2. Use the release version and replace UpdateManager.py with https://github.com/pyload/pyload/raw/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py

**Comment by sebaro11** [comment]
@GammaC0de I go with the first option, because the second one did not work for me. ^^
Thank for the fast help!
(For a MOCH plugin request I guess I have to open a new 'issue', am I right?)

**Comment by GammaC0de** [comment]
👍 Correct.

Closing.
