### ISSUE TITLE
API for ReCaptcha v2

### ISSUE THREAD

**Issue by funta23** [pyload/pyload#3122]
Here is an answer from 9kw staff to my question if they can help fix 9kw pyload plugin so that hosters using ReCaptcha can work again. 
Not sure what is needed to provide the that API and if work from other mentioned projects might help here.

From 9kw:
> Pyload has no api for recaptcha v2. This problem is from pyload.
> Our captcha service has rcv2 support since months.
> 
> We can only update the plugin for 9kw after the pyload api has rc2 support for captcha services.
> 
> Other tools like jdownloader 2 (since months!) and fritzload (few days) already "fixed".

**Comment by Michi-F** [comment]
I've just looked at their API, it seems to be quite simple:
https://www.9kw.eu/hilfe_more.html

The best news for pyload, running in low power devices:
> All steps have now been completed successfully without browser emulation.
Sounds promising! You don't even need to load a captcha within pyload, you only need the site-key of  the site and do some requests to 9kw.

I'll have a look on how this can be implemented within pyload and the hoster-plugins.

**Comment by GammaC0de** [comment]
@funta23 Can you ask the support why I'm not getting any answer from 9kw (I try every 3 second for a duration of 300 seconds)?
```
session_id = self.load("https://www.9kw.eu/index.cgi?apikey=<9KW_API_KEY>&action=usercaptchaupload&interactive=1&file-upload-01=6LdatrsSAAAAAHZrB70txiV5p-8Iv8BtVxlTtjKX&oldsource=recaptchav2&pageurl=http://www.share-online.biz/dl/WICYFWWOSP")

result = ""
while (!result):
    result  = self.load("https://www.9kw.eu/index.cgi?apikey=<9KW_API_KEY>&action=usercaptchacorrectdata&id=<session_id>")
    time.sleep(3)

```

**Comment by Michi-F** [comment]
Good news: I managed to get 9kw working with share-online: [https://github.com/Michi-F/pyload/tree/stable](https://github.com/Michi-F/pyload/tree/stable)
The code (up to commit [https://github.com/Michi-F/pyload/commit/2ab8644ef8f24233d0b4438c7b6612fd482a7726](Michi-F/pyload @ 2ab8644) is working so far.

So far you can add a new download link in pyload, and everything else is handled by pyload and the 9kw plugin!
Notice that I had to patch the 9kw-plugin, so you have to use my "Captcha_9kW.py" plugin, and not the current one of pyload or from the 9kw-website.

What's not working: the captcha isn't visible in the Webinterface, only the 9kw plugin can solve the recaptcha v2 so far. I'm currently working on the pyplex template to display the captcha in an iframe, where the user can solve it (solution with tampermonkey, as explained in the other thread).
I'll give you an update on this :)

@GammaC0de 
You're using the wrong site-key, the new one for recaptcha v2 on shareonline is "6LdnPkIUAAAAABqC_ITR9-LTJKSdyR_Etj1Sf-Xi"

**Comment by Michi-F** [comment]
Update: https://github.com/pyload/pyload/issues/3074#issuecomment-370273042

short: share-online + 9kw is working, without the need of selenium/firefox on the pyload server

**Comment by pyblub** [comment]
Just a question about 9kw: What is the advantage of 9kw?

You can solve captchas to let your captchas be solved, right? But you have to solve more as you normally would, because you earn less credits than you pay per captcha (which makes sense from the perspective of the creators of the service).
You can pay for the captchas being solve, I think? But then you can buy a premium account as well?

This is not supposed to be criticism, I just really want to understand how I can benfit from 9kw.

That being said, I think we should support it anyway, as people seem to want to use it.

**Comment by GammaC0de** [comment]
@pyblub For now, this is the only solution for low-power devices such as NASs.

P.S.
Sorry for not doing any progress on #3074 , I have less spare time latly.

**Comment by Michi-F** [comment]
@pyblub 

Yes, for heavy users you can buy a premium account as well, then you don't have any captcha problems, too :)
I use 9kw.eu because I don't download that much, so a premium account doesn't pay off for me.
For 5€ you can solve about >1000 captchas (and thus download >1000 files), which is enough for several months for me. Plus it's hoster-independent. A premium account would cost ~5€/month, for one hoster only. So 9kw is simply cheaper for me.
I don't want to advertise ist, it's just a low cost & easy solution for me.

The low download speed (compared to premium) doesn't matter for me, because mostly I don't neet the files on the same day. Therefore I can use it together with pyload running on a raspberry, and the files can be downloaded overnight.

So the reason I'm using pyload is because it supports 9kw and runs smoothly on a low-power device (like a raspberry) which I can run 24/7 ;)

**Comment by funta23** [comment]
@GammaC0de : Guess It'd be best if you'd ask on the 9kw contact form:
https://www.9kw.eu/useraddticket.html

**Comment by Michi-F** [comment]
FilerNet is already working, see other issue:
https://github.com/pyload/pyload/issues/3074#issuecomment-370865920

And 9kw plugin is working again together with the recaptcha v2 hosters!

**Comment by funta23** [comment]
Really great work guys! Thanks for the quick fix!
