### ISSUE TITLE
How do I make pyload work in my Qnap NAS ?

### ISSUE THREAD

**Issue by Sbrunei** [pyload/pyload#3130]
My NAS is QNAP TS-228.
I have downloaded pyLoad_4.9_arm-x19.qpkg, successfully installed the qpkg manually via app center.
After installing, when I clicked at pyload app icon, it would redirect to qnap ip address, and nothing happens.
Can anyone help me?

**Comment by fugitif** [comment]
look here maybe
https://www.forum-nas.fr/viewtopic.php?f=21&t=2273&start=200

**Comment by Sbrunei** [comment]
@fugitif thanks, but I have already tried that link before.. and that is only for x86... my QNAP is ARM...

**Comment by GammaC0de** [comment]
https://www.qnapclub.eu/en/qpkg/model/download/138045/QPyload_170116_arm-x41.qpkg

**Comment by 4urele** [comment]
Hi,

As far as I remember I had to switch to entware-ng months ago (or last year) because some qnap packages were not updated (I don't remember what python package had to be updated). Mayby today it is back to normal... 
If you are not affraid by ssh and commandline entware is a great alternative.

(I also put the pyload user plugins in the shared download directory to update pyload when the UpdateManager fail)

Aurèle

**Comment by Sbrunei** [comment]
hi @4urele 
Should I use entware-ng alongside qpyload/pyload, or... just use qpyload/pyload independently? 
I am no actually afraid of ssh/commandline or anything, as long as there is a clear instructions on how to do it.
My goal is simple, I wanted to have an app installed in my QNAP NAS that can handle premium downloads, and possibly automatically unrar them.... (just like what pyLoad is for)
