### ISSUE TITLE
Keepshare-Plugin doesn´t work

### ISSUE THREAD

**Issue by elgreco29** [pyload/pyload#3384]
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

Activating K2s-Plugin crashes pyload

Hi, after i added the k2s-plugin my pyload asks for a captcha and the settings are not available. Only a hard reset opens the settings again. Please fix it.

**Comment by GammaC0de** [comment]
Please read #3238 and report if it helped. 

 
 
   elgreco29<notifications@github.com> wrote:   
Type of ticket:
   
   -  Plugin request
   -  Feature request
   -  Bug report
   -  Question
   -  Other

Summary:

Activating K2s-Plugin crashes pyload

Hi, after i added the k2s-plugin my pylopad asks for a captcha and the settings are not available. Only a hard reset opens the settings again. Please fix it.

How to reproduce:

Expected behavior:

Actual behavior:

Debug log:

References:

**Comment by igel-kun** [comment]
@elgreco29 sometimes, Keep2share.cc asks for a captcha to allow authentication (if you stored login credentials in pyload). I suspect that the account plugins are loaded before the configuration logic is loaded. If you solve then captcha, your configuration should be accessible again.
See also https://github.com/pyload/pyload/issues/3376#issuecomment-489330576_

**Comment by GammaC0de** [comment]
> after i added the k2s-plugin my pyload asks for a captcha and the settings are not available

Have you tried to solve the captcha?

**Comment by elgreco29** [comment]
It´s crazy, today it works like a charm.
