### ISSUE TITLE
Using it with Firefox

### ISSUE THREAD

**Issue by gerroon** [pyload/pyload#3449]
Hi

I am trying to use Pyload with Firefox 69 so I installed the Fire-Pyload addon however I cant get it to work on the otherhand the PylCEX for Chrome seems to work. 

Is there any other way to use or send links to Pyload from Firefox sicne the addon does not seem to work somehow?

thanks

**Comment by GammaC0de** [comment]
pyLoad does not require any addon besides tampermonkey to work.
You simply open your browser and enter the URL `http://<PYLOAD_IP>:8000`

**Comment by gerroon** [comment]
Yes it does not, but I want to be able to download or send downloads to Pyloads without going to the Pyload page.

**Comment by GammaC0de** [comment]
I don't know why you would want to do that, but Fire-Pyload is not developed by the pyLoad team, you should contact the developer (sebastien.zabala@free.fr) for support.

**Comment by gerroon** [comment]
I do not know why it is making it harder, I am not asking about support for the Firefox addon. I am asking if there is another way I can send download links to Pyload without opening the web page.

Why I want that? Because it is faster that way.

**Comment by GammaC0de** [comment]
Oh, OK, so you should have asked that. There is pyload-bookmarklet in our github repohttps://github.com/pyload/pyload-bookmarklet

Hope it helps.  
 
   gerroon<notifications@github.com> wrote:   
I do not know why it is making it harder, I am not asking about support for the Firefox addon. I am asking if there is another way I can send download links to Pyload without opening the web page.

Why I want that? Because it is faster that way.
