### ISSUE TITLE
ExtractArchive does not start

### ISSUE THREAD

**Issue by GottHeit** [pyload/pyload#3513]
Hej, since today ExtractArchive suddenly does not work anymore (worked a few days ago).
Can´t even see it starting/trying to extract in the log. Did not change anything and have no idea how to fix. Thanks!

> 

275 | 13.02.2020 19:34:19 | INFO | Download finished: hqxBlacHradsiMAdgfAtdsh.part3.rar
-- | -- | -- | --
276 | 13.02.2020 19:34:19 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
277 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669510]: File saved
278 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669510]: Checking download...
279 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669511]: File saved
280 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669511]: Checking download...
281 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669510]: File is OK
282 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: File is OK
283 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: Checking file (with built-in rules)...
284 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: Checking file (with built-in rules)...
285 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: Checking file (with custom rules)...
286 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: Checking file (with custom rules)...
287 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: Checking for link errors...
288 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: Checking for link errors...
289 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: No errors found
290 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: No errors found
291 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: No errors found
292 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: No errors found
293 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
294 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
295 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
296 | 13.02.2020 19:35:39 | INFO | Download finished: hqxBlacHradsiMAdgfAtdsh.part2.rar
297 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
298 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
299 | 13.02.2020 19:35:39 | INFO | Package finished: hqxBlacHradsiMAdgfAtdsh
300 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `package_finished`
301 | 13.02.2020 19:35:39 | INFO | Download finished: hqxBlacHradsiMAdgfAtdsh.part1.rar
302 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder `download_finished`
303 | 13.02.2020 19:35:40 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
304 | 13.02.2020 19:35:40 | DEBUG | All downloads processed
305 | 13.02.2020 19:35:40 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
306 | 13.02.2020 19:35:40 | DEBUG | All downloads processed
307 | 13.02.2020 19:35:40 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_finished`
308 | 13.02.2020 19:35:40 | DEBUG | All downloads finished

**Comment by GammaC0de** [comment]
1. Restart pyload2. Refresh your pyload installation using the instructions in #3283

 

GottHeit<notifications@github.com> wrote:   
Hej, since today ExtractArchive suddenly does not work anymore (worked a few days ago).
Can´t even see it starting/trying to extract in the log. Did not change anything and have no idea how to fix. Thanks!



| 275 | 13.02.2020 19:34:19 | INFO | Download finished: hqxBlacHradsiMAdgfAtdsh.part3.rar |
| 276 | 13.02.2020 19:34:19 | DEBUG | ADDON ExternalScripts: No script found under folder download_finished |
| 277 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669510]: File saved |
| 278 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669510]: Checking download... |
| 279 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669511]: File saved |
| 280 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669511]: Checking download... |
| 281 | 13.02.2020 19:35:38 | INFO | HOSTER UploadedTo[669510]: File is OK |
| 282 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: File is OK |
| 283 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: Checking file (with built-in rules)... |
| 284 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: Checking file (with built-in rules)... |
| 285 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: Checking file (with custom rules)... |
| 286 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: Checking file (with custom rules)... |
| 287 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: Checking for link errors... |
| 288 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: Checking for link errors... |
| 289 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: No errors found |
| 290 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: No errors found |
| 291 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669511]: No errors found |
| 292 | 13.02.2020 19:35:39 | INFO | HOSTER UploadedTo[669510]: No errors found |
| 293 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder download_processed |
| 294 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder download_processed |
| 295 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder package_processed |
| 296 | 13.02.2020 19:35:39 | INFO | Download finished: hqxBlacHradsiMAdgfAtdsh.part2.rar |
| 297 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder download_finished |
| 298 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder package_processed |
| 299 | 13.02.2020 19:35:39 | INFO | Package finished: hqxBlacHradsiMAdgfAtdsh |
| 300 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder package_finished |
| 301 | 13.02.2020 19:35:39 | INFO | Download finished: hqxBlacHradsiMAdgfAtdsh.part1.rar |
| 302 | 13.02.2020 19:35:39 | DEBUG | ADDON ExternalScripts: No script found under folder download_finished |
| 303 | 13.02.2020 19:35:40 | DEBUG | ADDON ExternalScripts: No script found under folder all_downloads_processed |
| 304 | 13.02.2020 19:35:40 | DEBUG | All downloads processed |
| 305 | 13.02.2020 19:35:40 | DEBUG | ADDON ExternalScripts: No script found under folder all_downloads_processed |
| 306 | 13.02.2020 19:35:40 | DEBUG | All downloads processed |
| 307 | 13.02.2020 19:35:40 | DEBUG | ADDON ExternalScripts: No script found under folder all_downloads_finished |
| 308 | 13.02.2020 19:35:40 | DEBUG | All downloads finished |

**Comment by GottHeit** [comment]
Thanks! Saw #3283 but was confused by post date. Thought, I already did that a year ago... did it again, but did not help. Then I found the following in the log. I had that package twice in the queue, so it wasn´t there anymore to extract by the second. Seems like pyload was waiting to extract that missing package. I added it again and after downloading and restarting pyload, alle packages are extracting one by one... 

Remembered I had that behaviour before, so might be a bug? 

> 

434 | 13.02.2020 21:07:42 | INFO | ADDON ExtractArchive: Check package: XXX
-- | -- | -- | --
435 | 13.02.2020 21:07:42 | DEBUG | ADDON UpdateManager: LOAD URL  https://raw.githubusercontent.com/pyload/updates/master/plugins.txt \|  redirect=True \| cookies=True \| get={'v': '0.4.9'} \| req=None \|  decode=True \| multipart=False \| post={} \| ref=True \| just_header=False
436 | 13.02.2020 21:07:42 | DEBUG | ADDON ExtractArchive: Targets for UnRar: [(669420,  '/i-data/a578d198/nfs/filme/downloads/XXX/EAGEGBGSHGSGG.part1.rar',  '/i-data/a578d198/nfs/filme/XXX')]
437 | 13.02.2020 21:07:42 | DEBUG | ADDON ExtractArchive: EAGEGBGSHGSGG.part1.rar \| File not found
438 | 13.02.2020 21:07:42 | INFO | pyLoad is up and running
439 | 13.02.2020 21:07:42 | DEBUG | ADDON ExtractArchive: Targets for SevenZip: [(669420,  '/i-data/a578d198/nfs/filme/downloads/XXX/EAGEGBGSHGSGG.part1.rar',  '/i-data/a578d198/nfs/filme/XXX')]
440 | 13.02.2020 21:07:42 | DEBUG | ADDON ExtractArchive: EAGEGBGSHGSGG.part1.rar \| File not found
441 | 13.02.2020 21:07:42 | INFO | ADDON UpdateManager: pyLoad is up to date!
