### ISSUE TITLE
Can't add my premium ddl.to account.

### ISSUE THREAD

**Issue by Vinnpinn** [pyload/pyload#3582]
### Describe the problem

I'm trying to add my ddl.to premium account to pyload. I've set it up to run in a docker container on my qnap NAS. When I try to add the account to pyload it says not valid in status and no under premium.
I've tried adding the same account in JDownloader and that works.

### Debug log

```
13.04.2020 18:03:38 INFO      ACCOUNT DdlTo: Adding user `vin*******`...
13.04.2020 18:03:38 INFO      ACCOUNT DdlTo: Relogin user `vin*******`...
13.04.2020 18:03:38 ERROR     ACCOUNT DdlTo: Could not login user `vin*******` | Bad server response: 503 Service Unavailable

```

**Comment by GammaC0de** [comment]
Are you using some kind of VPN?

**Comment by Vinnpinn** [comment]
No I don't. I even tried running pyload on my windows machine and I get
the same error. I can connect to ddl.to without any problems and downloads
with the premium account work fine from jdownloader, running form the same
network.

Am Mo., 13. Apr. 2020 um 21:54 Uhr schrieb GammaC0de <
notifications@github.com>:

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

Can you provide debug logs?

**Comment by Vinnpinn** [comment]
I sent you my account data, attached is the log file after enabling debug mode and trying to add the account.
[log.txt](https://github.com/pyload/pyload/files/4471668/log.txt)

**Comment by Tockra** [comment]
Same issue here. Since a while I can't login with pyload to ddl.to ...

**Comment by GammaC0de** [comment]
I can confirm this is a cloudflare issue.

**Comment by Tockra** [comment]
Can you solute this problem?

**Comment by GammaC0de** [comment]
Now it works - it seems they turned cloudflare off at-the-moment..

**Comment by Vinnpinn** [comment]
Can confirm that it does work now, downloads work aswell.

![image](https://user-images.githubusercontent.com/26883610/79284863-2ea8fe80-7ebc-11ea-9f8b-ce67116ec314.png)

**Comment by Tockra** [comment]
ddl.to still make problems:
```bash
pyload_1  | 15.04.2020 02:15:29 INFO      Download restarted: name.2019.GERMAN.1080P.WEB.H264-WAYNE.part6.rar | Fallback to free processing
pyload_1  | 15.04.2020 02:15:29 INFO      Download starts: name.2019.GERMAN.1080P.WEB.H264-WAYNE.part6.rar
pyload_1  | 15.04.2020 02:15:29 WARNING   HOSTER DdlTo[92]: Plugin may be unstable
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Grabbing link info...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: Direct download link not found
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: Checking for link errors...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: No errors found
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: Processing as premium download...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: Checking for link errors...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: No errors found
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[93]: Waiting 1 seconds...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Link name: name.2019.GERMAN.1080P.WEB.H264-WAYNE.part6.rar
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Link size: 1023.00 MiB (1072693248 bytes)
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Link status: online
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Processing url: https://ddl.to/XXXXXXX
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Checking for link errors...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: No errors found
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Processing as free download...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: Checking for link errors...
pyload_1  | 15.04.2020 02:15:29 INFO      HOSTER DdlTo[92]: No errors found
pyload_1  | 15.04.2020 02:15:29 WARNING   HOSTER DdlTo[92]: Free download failed | Max retries reached
pyload_1  | 15.04.2020 02:15:29 WARNING   Download failed: name.2019.GERMAN.1080P.WEB.H264-WAYNE.part6.rar | Max retries reached

```

**Comment by Tockra** [comment]
At the moment:
```

395 | 15.04.2020 16:13:46 | WARNING | Download failed: https://ddl.to/XXXXX \| No JSON object could be decoded: line 1 column 0 (char 0)
-- | -- | -- | --
396 | 15.04.2020 16:13:46 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: https://ddl.to/pjpwchivhsfr (pid:17)
397 | 15.04.2020 16:13:46 | INFO | ADDON UnSkipOnFail: No duplicates found


```

**Comment by d30r** [comment]
Getting errors downloading from ddl.to since today:

WARNING | Download failed: https://ddl.to/XXXXXXXXXXX \| Expecting value: line 1 column 1 (char 0)

**Comment by Phist0ne** [comment]
The api url changed. Until an official update is realeased, you can change the constant in plugins/hoster/DdlTo.py yourself in line 38 change 
```python
    API_URL = "https://ddl.to/api/"
```
to
```python
    API_URL = "https://api-v2.ddl.to/api/"
```

**Comment by d30r** [comment]
> The api url changed. Until an official update is realeased, you can change the constant yourself in plugins/hoster/DdlTo.py, line 38 change:
> 
> ```python
>     API_URL = "https://ddl.to/api/"
> ```
> 
> to
> 
> ```python
>     API_URL = "https://api-v2.ddl.to/api/"
> ```

Thank you! Now it works like it should.

**Comment by godfuture** [comment]
Have same issue as thread opener. Was this issue fixed by changes mentioned in this ticket? I have updated the docker container and done a restart to update plugins.

1034 | 09.05.2020 02:26:23 | INFO | starte pyLoad 0.4.20
-- | -- | -- | --
1035 | 09.05.2020 02:26:23 | INFO | Benutze Home-Verzeichnis: /config
1036 | 09.05.2020 02:26:23 | INFO | Aktivierte Plugins: ClickNLoad, EventMapper, ExternalScripts,  ExtractArchive, HotFolder, UnSkipOnFail, UpdateManager,  UserAgentSwitcher, XFileSharing
1037 | 09.05.2020 02:26:23 | INFO | Deaktivierte Plugins: AntiStandby, AntiVirus, AppriseNotify,  BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha,  DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, IRC,  ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker,  MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev,  TransmissionRPC, WindowsPhoneNotify, XMPP
1038 | 09.05.2020 02:26:23 | INFO | Downloadzeit: True
1039 | 09.05.2020 02:26:23 | INFO | Starte ThriftBackend: 0.0.0.0:7227
1040 | 09.05.2020 02:26:23 | INFO | Freier Speicher: 673.69 GiBGB
1041 | 09.05.2020 02:26:23 | INFO | Aktiviere Accounts...
1042 | 09.05.2020 02:26:24 | INFO | Starting threaded webserver: :::8000
1043 | 09.05.2020 02:26:24 | INFO | ACCOUNT DdlTo: Adding user `c*******`...
1044 | 09.05.2020 02:26:24 | INFO | ACCOUNT DdlTo: Login user `c*******`...
1045 | 09.05.2020 02:26:28 | ERROR | ACCOUNT DdlTo: Could not login user `c*******` \| Bad server response: 503 Service Unavailable
