### ISSUE TITLE
Torrent support without downloader

### ISSUE THREAD

**Issue by mariomare22** [pyload/pyload#3587]
### Your question

Hi, I have installed PyLoad in a Docker container, all is good and working except torrent support.
I would like to know why Torrent files are not downloaded directly but they need RealDeBrid account.

just a little comparison, Aria2 ha torrent support but no .DLC support. :-) that is why i switched to pyload. Thanks a lot

**Comment by treysis** [comment]
Because pyload doesn't include a torrent client, so it's using RealDebrid for that. Implementing a torrent client isn't that straightforward. There are some bittorrent python clients/libraries, but integrating them would be a lot of work. I don't think this is within the scope of what pyLoad is supposed to do.

**Comment by mariomare22** [comment]
thanks a lot for the rocket speed answer
