### ISSUE TITLE
[External Scripts] Won't Run

### ISSUE THREAD

**Issue by markuswhiteus** [pyload/pyload#3635]
I'm running Pyload on my raspberry pi 4 trying to get it to run my filebot script to rename and move the files after the download has completed the script works when launched manually however it doesn't seem to be launching at all when a download finishes.

my script is found at /opt/pyload/scripts/download_finished/ExternalScript.sh

I have also set up the permissions so this script is executable by anyone.

```
#!/bin/bash

sudo filebot -script fn:amc --output "/mnt/volume/shares/plex" --action move -non-strict "/mnt/volume/shares/torrents/RD" --log-file amc.log --def excludeList=amc.txt
```

Pretty new to all this so apologies if its just a noob error.

**Comment by GammaC0de** [comment]
This is not where you are supposed to put the script:Go to http://<PYLOAD_IP>/info and see what is the value of "home folder", there should be a scripts folder. 

 
 
  Mark White<notifications@github.com> wrote:   


I'm running Pyload on my raspberry pi 4 trying to get it to run my filebot script to rename and move the files after the download has completed the script works when launched manually however it doesn't seem to be launching at all when a download finishes.

my script is found at /opt/pyload/scripts/download_finished/ExternalScript.sh

`
#!/bin/bash

sudo filebot -script fn:amc --output "/mnt/volume/shares/plex" --action move -non-strict "/mnt/volume/shares/torrents/RD" --log-file amc.log --def excludeList=amc.txt
`

Pretty new to all this so apologies if its just a noob error.

**Comment by markuswhiteus** [comment]
> This is not where you are supposed to put the script:Go to http://<PYLOAD_IP>/info and see what is the value of "home folder", there should be a scripts folder.  Mark White<notifications@github.com> wrote: I'm running Pyload on my raspberry pi 4 trying to get it to run my filebot script to rename and move the files after the download has completed the script works when launched manually however it doesn't seem to be launching at all when a download finishes. my script is found at /opt/pyload/scripts/download_finished/ExternalScript.sh ` #!/bin/bash sudo filebot -script fn:amc --output "/mnt/volume/shares/plex" --action move -non-strict "/mnt/volume/shares/torrents/RD" --log-file amc.log --def excludeList=amc.txt ` Pretty new to all this so apologies if its just a noob error. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

That is where my home folder is:

pyLoad version:0.4.20
Installation Folder:/opt/pyload
Config Folder:/root/.pyload

**Comment by GammaC0de** [comment]
Sorry, I meant config folder

 
 
  Mark White<notifications@github.com> wrote:   



This is not where you are supposed to put the script:Go to http://<PYLOAD_IP>/info and see what is the value of "home folder", there should be a scripts folder.  Mark Whitenotifications@github.com wrote: I'm running Pyload on my raspberry pi 4 trying to get it to run my filebot script to rename and move the files after the download has completed the script works when launched manually however it doesn't seem to be launching at all when a download finishes. my script is found at /opt/pyload/scripts/download_finished/ExternalScript.sh #!/bin/bash sudo filebot -script fn:amc --output "/mnt/volume/shares/plex" --action move -non-strict "/mnt/volume/shares/torrents/RD" --log-file amc.log --def excludeList=amc.txt Pretty new to all this so apologies if its just a noob error. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


That is where my home folder is:

pyLoad version:0.4.20
Installation Folder:/opt/pyload
Config Folder:/root/.pyload

**Comment by markuswhiteus** [comment]
Ah thats where i've been going wrong then theyve been in home not config.

Tested and now works many thanks for your help!
