### ISSUE TITLE
DebridlinkFr Torrent Plug-in

### ISSUE THREAD

**Issue by yonix06** [pyload/pyload#3641]
Hello !
### Describe the plugin

A plug-in for adding torrent on debrid-link.fr, like the one there is for realdebrid.com
And a way to delete them once they have reach a certain ratio.

### Sample resources

An api is avaible and managing the torrenting is possible, debrid-link.fr/api_doc/v2/seedbox-list

### Additional references

I tried to make my own plugin by copying the realdebrid one, but im way too noob to do this so i am asking for a bit of help :). I prefer to use this service provider because he allow to stay in seed.
I think there is a way to ask to remove the file on the seedbox once it reaches a certain ratio, at least from what i have read in the api.

I am willing to provide a premium account for any test regarding the development of a plugin like this one.

**Comment by lTimeLordl** [comment]
It would be great to migrate to the API v2 + Oauth2.

Deleting torrents change nothing on Debrid-Link side. Torrents are automatically removed of the servers when them reach seed/storage limits. Deleting torrents just clean your torrents list, so i'm not sure this feature is required. As you want.

**Comment by yonix06** [comment]
Effectively, it does not change a thing on the debrid link side, but it is usefull if you are on a private tracker for torrenting. 
i dont remember if we have to set the ratio on their website or in the seedbox tho, maybe i was asking for a thing that is not possible, anyway,

Regarding the plug-in itself, it would be great to have something similar to the realdebridcomtorrent one, but for debridlinkfr.

**Comment by GammaC0de** [comment]
>realdebridcomtorrent one, but for debridlinkfr.

Sadly, removing the torrent from the server makes the download links invalid :(

**Comment by lTimeLordl** [comment]
Thanks for the update but i think using the "password" "grant_type" could be better than generating tokens in separate script. https://debrid-link.com/api_doc/v2/oauth2-password

**Comment by GammaC0de** [comment]
Password can generate cpatcha requests when trying to log in which pyload does not support 
"password: Username/Password (Not recommended because a captcha and other errors can occur)." 
 
 
   lTimeLordl<notifications@github.com> wrote:   


Thanks for the update but i think using the "password" "grant_type" could be better than generating tokens in separate script. https://debrid-link.com/api_doc/v2/oauth2-password

**Comment by yonix06** [comment]
I think I saw the feature being updated on the last version of pyload, imma go check this but I wanted to say thanks you for looking into it, it's awesome.
Need to be at home to follow this properly tho

**Comment by lTimeLordl** [comment]
Captcha will be requested only when a IP make multiple errors or when you flood this endpoint.

password grant_type is better than a separate script to generate the session because if an user configure it username/password on PyLoad settings you will send the username/password as access_token/refresh_token on our API. On Debrid-Link side we could log the request when an error occur for debug and the password could be clearly logged (because you will sent it as refresh_token if user not configured properly). So this is a very bad practice for the implementation of our API.

Please update it to use the password grant_type.

**Comment by GammaC0de** [comment]
@lTimeLordl Do you work at Debridlink?

**Comment by lTimeLordl** [comment]
Yes I work at Debrid-Link, if you need a premium account for the test, contact our support ;)
