### ISSUE TITLE
py-OpenSSL: missing although installed

### ISSUE THREAD

**Issue by DoS007** [pyload/pyload#4035]
### Description

The setup test gives me "py-OpenSSL: missing", but I installed it successfully with `python -m pip install pyOpenSSL`? (Using windows 10)

### Debug log

```

```

### Additional references

https://pypi.org/project/pyOpenSSL/
https://stackoverflow.com/a/62190111

### Screenshots

![grafik](https://user-images.githubusercontent.com/11618958/140648239-92f74c52-fc4a-478a-a8ba-8b27f9444d89.png)

**Comment by GammaC0de** [comment]
py-OpenSSL is nedded only if wou want to use ssl with the webui, for portable use it is not nessary. 

 

***@***.***> wrote:   


Assigned #4035 to @GammaC0de.


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DoS007** [comment]
@GammaC0de Ah, ok. 

Could you please confirm for security reasons that pyload will use ssl/tls for downloadings processes even if py-openssl isn't installed?

**Comment by GammaC0de** [comment]
Pyload will use SSL if the plugin/website supports it (which is most of them nowadays)

**Comment by DoS007** [comment]
@GammaC0de Thank you.

**Comment by GammaC0de** [comment]
👍
