### ISSUE TITLE
Two pyload-installations causing logouts when opened in different browser tabs

### ISSUE THREAD

**Issue by NorfolkXX** [pyload/pyload#4512]
Hi,

not sure where this bug comes from, so I call it a question instead. 

I ran two installations of pyload on different ports at the same server.

When accessing both ports in different browsers or in the same browser but one in a regular chrome tab and the other in an incognito tab, everything is fine and they can be used in parallel.

But when opening both installations in two regular chrome tabs - or two incognito chrome tabs - they keep logging out each other, so each time I switch tab, I'm back at the login-page. 

This makes it impossible to use it this way. It did work in v0.4.20. I have the impression, the two sessions are interfering somehow.

PS: Why would I need such? The two installations use different download-directories, different plugin-settings and sometimes also have different plugins active at all. I think that's not possible with only one installation.

**Comment by OzzieIsaacs** [comment]
I guess the problem is, that both instances store the "logged-in" information in a cookie with the same name and both instances run on the same host:
![grafik](https://github.com/user-attachments/assets/63055394-eb13-498a-ad1d-a2b6181b3cff)

If you change :
https://github.com/pyload/pyload/blob/76dd155ff7b8b63731b383e45f934afaf05ef995/src/pyload/webui/app/__init__.py#L114

in the code to:
`        app.config["SESSION_COOKIE_NAME"] = "pyload_session" + os.environ.get('COOKIE_PREFIX', "")`

Then you can give the cookie of each instance a postfix, which can be set via the environment variable "COOKIE_PREFIX" on startup. (Google knows how to do it, if in doubt how to do it). 

I didn't check it in this particular case, but use a similar approach for a similar web-app

**Comment by NorfolkXX** [comment]
Thank you, works like a charm.

I followed your lead but am lacking proper knowledge on python and stuff. So realizing I use different ports, I modified this line:
`app.config["SESSION_COOKIE_NAME"] = "pyload_session" `
to add the port-number into the cookie-name like this: 
`app.config["SESSION_COOKIE_NAME"] = "pyload_session" + str(app.config["PYLOAD_API"].get_config_value("webui", "port"))` 

@GammaC0de - Not sure if this is just a dirty hack working in my case, but if it's valid, maybe commit such change to the develop-code?
