### ISSUE TITLE
CloudFlare DDoS protection

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#582]
Heya,
I'm recently having problems accessing some hosters (like upstore.net) through public proxies: I'm getting the following HTTP answer:

```
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
  </style>
  <script type="text/javascript">
  //<![CDATA[
  (function(){
    var onReady = function( callback ){
        var addListener = document.addEventListener || document.attachEvent,
            eventName = document.addEventListener ? 'DOMContentLoaded' : 'onreadystatechange';
        addListener.call(document, eventName, function(){ callback(); }, false );
    }

    onReady(function(){
      var content = document.getElementById('cf-content');
      content.style.display = 'block';

      setTimeout(function(){
        var t,r,a,f;
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;
        r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length);
        t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        a.value = 2+38*10;
        a.value = parseInt(a.value, 10) + t.length;
        f.submit();
      }, 5850);
    });
  })();
  //]]>
</script>

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    <img src="/cdn-cgi/images/spinner-2013.gif" id="spinner" />
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> upstore.net.</h1>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="fd5423e01b2280721f8b7a0702f7915f"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>


          <div class="attribution"><a href="http://www.cloudflare.com/" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a></div>
      </td>
    </tr>
  </table>
</body>
</html>
```

which claims to be some DDoS protection. Does pyload have some automation to abide by the (5sec) waiting time incurred by this mechanism? And if not, should there be one?

**Comment by GammaC0de** [comment]
Looking for sample URLs with CloudFlare DDoS protection for testing..

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/f0c49a8db0671219e6e2e225880488cb71bafa90 Created new hook plugin [CloudFlareDdos](https://github.com/pyload/pyload/blob/f0c49a8db0671219e6e2e225880488cb71bafa90/module/plugins/hooks/CloudFlareDdos.py) (not active by default)
Currently supports only `SimpleHoster` based plugins.

Reuires a patched [HTTPRequest.py](https://github.com/GammaC0de/pyload/blob/1f8acaefb33faacbe85fc00ae961f1ab7ae6e8e8/pyload/network/HTTPRequest.py) to resolve https://github.com/pyload/pyload/issues/2565

Unfortunately,
I could not test the ddos challenge because I could not find a site with it (https://github.com/pyload/pyload/issues/582#issuecomment-256302192)

**Comment by igel-kun** [comment]
Ah nice work, thanks!
Indeed for testing, I found it most reliable to configure some public proxy (or a TOR proxy) and visit any respectible hoster. In 90% of cases, this brings up some form of CloudFlare for me.

**Comment by GammaC0de** [comment]
Hi , Can you explain further please how to setup to this ? Can you give me a sample URL that shows CloudFlare when using proxy ? 
 

   
Ah nice work, thanks!
Indeed for testing, I found it most reliable to configure some public proxy (or a TOR proxy) and visit any respectible hoster. In 90% of cases, this brings up some form of CloudFlare for me.

**Comment by igel-kun** [comment]
Yeah, sure.
**Step1**: configure an overly used proxy server:
Option 1: use TOR: install and run [The Onion Router](https://www.torproject.org/). This is the more reliable choice.
Option 2: public proxy: configure a proxy from, for example [this list](https://free-proxy-list.net/) - you might have to try several of them, actually as sometimes they are down, sometimes they are not overused enough.
**Step2**: try to download anything from... let's say... [openload](https://openload.co/f/iLw6mOz6YYk) _disclaimer: I have nothing to do with this link, I found it googling for "http://openload"_

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/467d69da6f77c5086caca733d49c7aef23fb44ff
OpenloadIo should now work with TOR, although I could not do the actual download because OpenloadIo reports:
`bandwidth usage too high (peak hours). out of capacity for non-browser downloads. please use browser download.`
but I got this error even without TOR either so it is not related to CloudFlare but just a temporary issue. 

Also when using OpenloadIo with TOR, you get "CloudFlare's security check page" (HTTP code 403) which asks you if you're human before you can continue.

I'm still looking for for a URL with "CloudFlare's DDoS protection page" (HTTP code 503) which you get a message 'just one moment' and a delay of 5 seconds and then automatically redirects you to the page.

**Comment by igel-kun** [comment]
Good job! Could be that CloudFlare changed their handling in the meantime (it's been a while).

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/44e60a1947a86ce7e8f7a0caaeb1c851880a0762
Added SimpleCrypter support.
Now tested and works with "CloudFlare's DDoS protection page".

Unless the bugs in `HTTPRequest` this could be closed.

**Comment by GammaC0de** [comment]
`HTTPRequest` issues are no more, closing.
