### ISSUE TITLE
privoxy and 503 issues

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#670]
hey everyone, I'm trying to use a privoxy as proxy, which has the habit of throwing http error 503 when something is temporarily unavailable (f.ex. its timeout is hit). Now, I'm trying to get pyload to recognize 503 as "temporary offline", so I excluded it from the range of bad ports and added

```
if hasattr(self, "req") and self.req.http.code == '503':
            self.tempOffline()
```

to the `getFileInfo` method of `SimpleHoster` (right before it calls `parseFileInfo`). Unfortunately, however, this didn't work. A quick debug output shows that self indeed has a `req` attribute and `self.req.http.code` is 0.
This leads to a parse error later on, throwing a debug file which shows that `self.html` is indeed the "there was a 503-error"-webpage that privoxy generates and wireshark told me that this exact webpage came with an error code 503. So why is `self.req.http.code=0`?

**Comment by bogeyman** [comment]
Well, I am also interested in this http error code 503. I use to download file from onlinetvrecorder.com and they deliver this code when your download is in a waiting queue and you should retry. There is also a "Retry-After" header, suggesting the time to wait. Because no one has answered to this issue yet, I am going to look into the code myself.

Question is: Is there any reason this should not be implemented in general?
