### ISSUE TITLE
plugin out of date: Keep2shareCC

### ISSUE THREAD

**Issue by alex9434** [pyload/pyload#964]
The plugin Keep2shareCC seems to be out of date:

18.12.2014 15:26:32 INFO      Download starts: http://k2s.cc/file/[deleted]
18.12.2014 15:27:18 WARNING   Download failed: [deleted] | Parse error: LINK_FREE_PATTERN not found | Plugin may be out of date

I could downlaod the file with the webbrowser

**Comment by dev-rke** [comment]
I got a similar error for each file started in free mode, after upgrading the plugin to v0.20:
WARNING	Download failed: source.zip | Parse error: Free download link not found | Plugin may be out of date 
ERROR	Error executing hooks: u'Keep2ShareCc'

I would assume that the ERROR_PATTERN has to be customized, so that self.checkErrors() find the error and will retry the download.

FYI: after updating the plugin the first time no download could be started. 
I had to change the plugin column in the link table of the sqlite database using
UPDATE link SET plugin = "Keep2ShareCc" WHERE plugin = "Keep2ShareCC";
to make it work again.
Keep an eye on "CC" vs. "Cc".
But now i've got two plugins in the userplugin folder: Keep2ShareCc.py and Keep2shareCc.py (first letter of "Share" vs. "share").
I'd assume you should rename the file to Keep2ShareCc.py (capitalized "S" in "Share"), due to the class name inside.

**Comment by vuolter** [comment]
Reminder: rewrite it using k2c API.

**Comment by Velociraptor85** [comment]
one has to register first to test this @alex9434 @dev-rke  please contact @GammaC0de on gitter if still interessted in this I will close this for now
